### ISSUE TITLE
ParallelUTest sporadically fails

### ISSUE THREAD

**Issue by vsbogd** [opencog/atomspace#2127] opened 2019-03-11 10:45 UTC
While running ParallelUTest in a loop, it fails at some point:
```
$ while ./tests/atoms/ParallelUTest; do echo ok; done
Running cxxtest tests (3 tests)[2019-03-11 10:43:15:237] [DEBUG] BEGIN TEST: test_parallel
0-count = 0

After first sleep (exit 0) 2.0001 secs past
1-count = 1

After second sleep (exit 0) 4.0003 secs past
2-count = 2

After third sleep (exit 0) 6.0006 secs past
3-count = 3

[2019-03-11 10:43:21:239] [DEBUG] END TEST: test_parallel
.[2019-03-11 10:43:21:239] [DEBUG] BEGIN TEST: test_join
elapsed time = 5.000992 seconds
2-count = 2

[2019-03-11 10:43:26:242] [DEBUG] END TEST: test_join
.[2019-03-11 10:43:26:242] [DEBUG] BEGIN TEST: test_throw
BFD: /home/vital/projects/atomspace-build/opencog/atoms/execution/libexecution.so: warning: loop in section dependencies detected
[2019-03-11 10:43:26:258] [ERROR] Backtrace:
           6 (apply-smob/1 #<catch-closure 7f3470886f40>)
           5 (apply-smob/1 #<catch-closure 7f347099cb20>)
In ice-9/eval.scm:
   187:27  4 (_ _)
   223:20  3 (proc #<directory (guile-user) 7f34724f9140>)
In unknown file:
           2 (%resolve-variable (7 . insdfasdfascr) #<directory (gui…>)
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound …" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 7f347099cae0> # #f "Unbo…" …)

ERROR: In procedure apply-smob/1:
Unbound variable: insdfasdfascr
ABORT: unbound-variable
 (/home/vital/projects/atomspace/opencog/guile/SchemeEval.cc:1068)
	Stack Trace:
	2: Logger.cc:513	  opencog::Logger::logva(opencog::Logger::Level, char const*, __va_list_tag*)
	3: Logger.cc:525	  opencog::Logger::Error::operator()(char const*, ...)
	4: exceptions.cc:55	  opencog::StandardException::parse_error_message(char const*, __va_list_tag*, bool)
	5: exceptions.cc:82	  opencog::StandardException::parse_error_message(char const*, char const*, __va_list_tag*, bool)
	6: exceptions.cc:142	  opencog::RuntimeException::RuntimeException(char const*, char const*, ...)
	7: SchemeEval.cc:1068	  opencog::SchemeEval::apply_v(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, opencog::Handle)
	8: SchemeEval.h:185	  opencog::SchemeEval::apply_tv(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, opencog::Handle)
	9: EvaluationLink.cc:839	  opencog::EvaluationLink::do_eval_scratch(opencog::AtomSpace*, opencog::Handle const&, opencog::AtomSpace*, bool)
	10: EvaluationLink.cc:548	crisp_eval_scratch()
	11: EvaluationLink.cc:452	crisp_eval_scratch()
	12: EvaluationLink.cc:325	bool_to_tv()
	13: shared_ptr_base.h:658	  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()
	14: [0xb8c80] ??() ??:0
	15: [0x76ba] ??() ??:0
	16: [0x10741d] ??() ??:0

[2019-03-11 10:43:26:258] [ERROR] Backtrace:
           6 (apply-smob/1 #<catch-closure 7f347099c7c0>)
           5 (apply-smob/1 #<catch-closure 7f34709abe60>)
In ice-9/eval.scm:
   187:27  4 (_ _)
   223:20  3 (proc #<directory (guile-user) 7f34724f9140>)
In unknown file:
           2 (%resolve-variable (7 . insdfasdfascr) #<directory (gui…>)
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound …" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 7f34709abe20> # #f "Unbo…" …)

ERROR: In procedure apply-smob/1:
Unbound variable: insdfasdfascr
ABORT: unbound-variable
 (/home/vital/projects/atomspace/opencog/guile/SchemeEval.cc:1068)
	Stack Trace:
	2: Logger.cc:513	  opencog::Logger::logva(opencog::Logger::Level, char const*, __va_list_tag*)
	3: Logger.cc:525	  opencog::Logger::Error::operator()(char const*, ...)
	4: exceptions.cc:55	  opencog::StandardException::parse_error_message(char const*, __va_list_tag*, bool)
	5: exceptions.cc:82	  opencog::StandardException::parse_error_message(char const*, char const*, __va_list_tag*, bool)
	6: exceptions.cc:142	  opencog::RuntimeException::RuntimeException(char const*, char const*, ...)
	7: SchemeEval.cc:1068	  opencog::SchemeEval::apply_v(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, opencog::Handle)
	8: SchemeEval.h:185	  opencog::SchemeEval::apply_tv(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, opencog::Handle)
	9: EvaluationLink.cc:839	  opencog::EvaluationLink::do_eval_scratch(opencog::AtomSpace*, opencog::Handle const&, opencog::AtomSpace*, bool)
	10: EvaluationLink.cc:548	crisp_eval_scratch()
	11: EvaluationLink.cc:452	crisp_eval_scratch()
	12: EvaluationLink.cc:325	bool_to_tv()
	13: shared_ptr_base.h:687	  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::_M_swap(std::__shared_count<(__gnu_cxx::_Lock_policy)2>&)
	14: [0xb8c80] ??() ??:0
	15: [0x76ba] ??() ??:0
	16: [0x10741d] ??() ??:0

[2019-03-11 10:43:26:377] [WARN] Caught exception in thread:
Backtrace:
           6 (apply-smob/1 #<catch-closure 7f3470886f40>)
           5 (apply-smob/1 #<catch-closure 7f347099cb20>)
In ice-9/eval.scm:
   187:27  4 (_ _)
   223:20  3 (proc #<directory (guile-user) 7f34724f9140>)
In unknown file:
           2 (%resolve-variable (7 . insdfasdfascr) #<directory (gui…>)
In ice-9/boot-9.scm:
   751:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound …" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 7f347099cae0> # #f "Unbo…" …)

ERROR: In procedure apply-smob/1:
Unbound variable: insdfasdfascr
ABORT: unbound-variable
 (/home/vital/projects/atomspace/opencog/guile/SchemeEval.cc:1068)
Segmentation fault (core dumped)
```
Maybe same reason with https://github.com/opencog/atomspace/issues/2126
Tested on a clean Release build in clean docker.

**Comment by vsbogd** [comment] 2019-03-11 11:08
It is not reproducible on `singnet` fork, so probably is not linked with https://github.com/opencog/atomspace/issues/2126

**Comment by vsbogd** [comment] 2019-03-11 12:05
bisect results:
```
$ git bisect log
# bad: [9a7562af66c79c9b01c3db1cc7e740b6011ceb7e] Merge pull request #2122 from linas/evo
# good: [e06e286dff56bffeedaac3803977055d7b442a43] Remove cruft
git bisect start '9a7562af66c79c9b01c3db1cc7e740b6011ceb7e' 'e06e286dff56bffeedaac3803977055d7b442a43'
# good: [40ff28501ef70b433dc1584fe9668ab1c9fa9e78] Remove more attentionbank stuff.
git bisect good 40ff28501ef70b433dc1584fe9668ab1c9fa9e78
# good: [eeb92e00ca2da6aaacdbc91e25e6640d939afc96] Touchup format, remove misleading ruminations
git bisect good eeb92e00ca2da6aaacdbc91e25e6640d939afc96
# good: [18e6329d5149180908c9e6acf7246b350dad0638] Add QueryLink unit test
git bisect good 18e6329d5149180908c9e6acf7246b350dad0638
# bad: [7ba864feee51f0097ce1f5c93751ebbe95a02fcc] whitespace fixes
git bisect bad 7ba864feee51f0097ce1f5c93751ebbe95a02fcc
# bad: [a2e744d9c8169e736bad2c911fce2ed1b4a2f989] Merge branch 'master' into guh
git bisect bad a2e744d9c8169e736bad2c911fce2ed1b4a2f989
# good: [e6a682b629f78c9692c83ce11ba82d02a3e8441c] Simplify/bugfix exception handling
git bisect good e6a682b629f78c9692c83ce11ba82d02a3e8441c
# good: [b11c9a848995168f06d3855e7ace1cb817909892] Return value-sets not handle-sets.
git bisect good b11c9a848995168f06d3855e7ace1cb817909892
# bad: [fd2171dc6e705a30e8ef4181ada592e0e4b54087] Merge pull request #2118 from linas/xp
git bisect bad fd2171dc6e705a30e8ef4181ada592e0e4b54087

$ git bisect view
commit fd2171dc6e705a30e8ef4181ada592e0e4b54087 (refs/bisect/bad)
Merge: 4bb63a55e cc68a2f19
Author: Linas Vepštas <linasvepstas@gmail.com>
Date:   Fri Mar 1 15:51:27 2019 -0600

    Merge pull request #2118 from linas/xp
    
    Fix exception handling in threads

commit cc68a2f19f769af802367195d09bcb071859dd91 (HEAD)
Author: Linas Vepstas <linasvepstas@gmail.com>
Date:   Fri Mar 1 14:58:35 2019 -0600

    Extend unit test for exception handling
```

**Comment by vsbogd** [comment] 2019-03-11 12:10
Problem is reproducible by test `ParallelUTest::test_throw` which is new and present only in `opencog` fork, so it is not clear by now whether the issue was introduced in `opencog` fork as well or it just reveals old issue.

**Comment by linas** [comment] 2019-03-11 17:54
The `test_throw()`  test *intentionally* forces an error, and then verifies that the error occurred. The unit test bases in the end, even though the log file is garbaged up with warnings.

There are several unit tests that intentionally throw errors, and then try to catch them. The `TS_ASSERT_THROWS_ANYTHING` and `TS_ASSERT_THROWS_NOTHING` and `TS_ASSERT_THROWS_ASSERT` cxxtest macros test verify that an error was or was not thrown.

Closing as "not a bug, working as designed".

**Comment by vsbogd** [comment] 2019-03-12 17:13
Test starts two threads in parallel, each of them throws and processes exception. During exception processing in each thread `Logger` calls `prt_backtrace` function which in turn calls `bfd_fopen` and `bfd_cache_init` functions. So `bfd_cache_init` is called in parallel from two different threads, and it seems it is not thread safe and leads to segfault. See [this issue](https://track.hpccsystems.com/browse/HPCC-15050) for similar problem.

Stack traces from threads:
ParallelLink thread:
```
(gdb) thread 16
[Switching to thread 16 (Thread 0x7fffe59a8700 (LWP 8551))]
#0  0x00007ffff290106b in bfd_cache_init () from /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
(gdb) bt
#0  0x00007ffff290106b in bfd_cache_init () from /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
#1  0x00007ffff2909756 in bfd_fopen () from /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
#2  0x00007ffff5141a71 in process_file (file_name=<optimized out>, addr=0x7fffe599cbb8, naddr=1)
    at /home/vital/projects/cogutil/opencog/util/backtrace-symbols.c:206
#3  0x00007ffff5141dda in oc_backtrace_symbols (buffer=buffer@entry=0x7fffe599cc70, size=size@entry=17)
    at /home/vital/projects/cogutil/opencog/util/backtrace-symbols.c:293
#4  0x00007ffff515f2e7 in prt_backtrace (oss=...)
    at /home/vital/projects/cogutil/opencog/util/Logger.cc:81
#5  0x00007ffff5160a8b in opencog::Logger::log (
    this=this@entry=0x7ffff5377b20 <opencog::logger()::instance>, 
    level=level@entry=opencog::Logger::ERROR, 
    txt="Backtrace:\n", ' ' <repeats 11 times>, "6 (apply-smob/1 #<catch-closure 7fffe5e51bc0>)\n", ' ' <repeats 11 times>, "5 (apply-smob/1 #<catch-closure 7fffe5e58f20>)\nIn ice-9/eval.scm:\n   187:27  4 (_ _)\n   223:20  3 (proc #<directory (guile-user) 7fffe7c47140>)\nIn unknown file:\n", ' ' <repeats 11 times>, "2 (%resolve-variable (7 . insdfasdfascr) #<directory (guile-user) 7fffe7c47140>)\nIn ice-9/boot-9.scm:\n   751:25  1 (dispatch-exception 0 unbound-variable (#f \"Unbound variable: ~S\" (insdfasdfascr) #f))\nIn unknown file:\n", ' ' <repeats 11 times>, "0 (apply-smob/1 #<catch-closure 7fffe5e58ee0> unbound-variable #f \"Unbound variable: ~S\" # #)\n\nERROR: In procedure apply-smob/1:\nUnbound variable: insdfasdfascr\nABORT: unbound-variable\n (/home/vital/projects/atomspace/opencog/guile/SchemeEval.cc:1068)")
    at /home/vital/projects/cogutil/opencog/util/Logger.cc:469
...
#17 0x00007ffff72ae218 in opencog::EvaluationLink::do_eval_scratch (as=0x640d50, evelnk=..., 
    scratch=0x640d50, silent=<optimized out>)
    at /home/vital/projects/atomspace/opencog/atoms/execution/EvaluationLink.cc:942
#18 0x00007ffff72b14ed in thread_eval (as=<optimized out>, evelnk=..., scratch=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    silent=<optimized out>)
    at /home/vital/projects/atomspace/opencog/atoms/execution/EvaluationLink.cc:300
#19 0x00007ffff4e5dc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007ffff56ae6ba in start_thread (arg=0x7fffe59a8700) at pthread_create.c:333
#21 0x00007ffff43a141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

JoinLink thread:
```
(gdb) thread 17
[Switching to thread 17 (Thread 0x7fffe51a7700 (LWP 8552))]
#0  0x00007ffff290106b in bfd_cache_init () from /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
(gdb) bt
#0  0x00007ffff290106b in bfd_cache_init () from /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
#1  0x00007ffff2909756 in bfd_fopen () from /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
#2  0x00007ffff5141a71 in process_file (file_name=<optimized out>, addr=0x7fffe519bb88, naddr=1)
    at /home/vital/projects/cogutil/opencog/util/backtrace-symbols.c:206
#3  0x00007ffff5141dda in oc_backtrace_symbols (buffer=buffer@entry=0x7fffe519bc40, size=size@entry=17)
    at /home/vital/projects/cogutil/opencog/util/backtrace-symbols.c:293
#4  0x00007ffff515f2e7 in prt_backtrace (oss=...)
    at /home/vital/projects/cogutil/opencog/util/Logger.cc:81
#5  0x00007ffff5160a8b in opencog::Logger::log (
    this=this@entry=0x7ffff5377b20 <opencog::logger()::instance>, 
    level=level@entry=opencog::Logger::ERROR, 
    txt="Backtrace:\n", ' ' <repeats 11 times>, "6 (apply-smob/1 #<catch-closure 7fffe6d53d00>)\n", ' ' <repeats 11 times>, "5 (apply-smob/1 #<catch-closure 7fffe6d59e00>)\nIn ice-9/eval.scm:\n   187:27  4 (_ _)\n   223:20  3 (proc #<directory (guile-user) 7fffe7c47140>)\nIn unknown file:\n", ' ' <repeats 11 times>, "2 (%resolve-variable (7 . insdfasdfascr) #<directory (guile-user) 7fffe7c47140>)\nIn ice-9/boot-9.scm:\n   751:25  1 (dispatch-exception 0 unbound-variable (#f \"Unbound variable: ~S\" (insdfasdfascr) #f))\nIn unknown file:\n", ' ' <repeats 11 times>, "0 (apply-smob/1 #<catch-closure 7fffe6d59dc0> unbound-variable #f \"Unbound variable: ~S\" # #)\n\nERROR: In procedure apply-smob/1:\nUnbound variable: insdfasdfascr\nABORT: unbound-variable\n (/home/vital/projects/atomspace/opencog/guile/SchemeEval.cc:1068)")
    at /home/vital/projects/cogutil/opencog/util/Logger.cc:469
...
#17 0x00007ffff72ae218 in opencog::EvaluationLink::do_eval_scratch (as=0x640d50, evelnk=..., 
    scratch=0x640d50, silent=<optimized out>)
    at /home/vital/projects/atomspace/opencog/atoms/execution/EvaluationLink.cc:942
#18 0x00007ffff72b1608 in thread_eval_tv (as=<optimized out>, evelnk=..., scratch=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    silent=<optimized out>, tv=0x66b5f0, returned_ex=0x7fffffffd080)
    at /home/vital/projects/atomspace/opencog/atoms/execution/EvaluationLink.cc:315
#19 0x00007ffff4e5dc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007ffff56ae6ba in start_thread (arg=0x7fffe51a7700) at pthread_create.c:333
#21 0x00007ffff43a141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Line numbers are not precise because I have added additional debug logging.

**Comment by linas** [comment] 2019-03-14 04:06
Ahh, OK, interesting.

**Comment by linas** [comment] 2019-03-14 04:12
Sorry, I did not notice the segfault at the very end. The opencog/cogutil#166 fix looks like a reasonable fix. Does that cure this bug? (Can we close this?)

**Closed** 2019-03-14 07:29 UTC
