### ISSUE TITLE
Matching Constant Pattern having NotLink throws Exception

### ISSUE THREAD

**Issue by Yidnekachew** [opencog/atomspace#1499] opened 2017-12-22 13:31 UTC
Pattern matching with this rule  

```
(define evaluate-constant-pattern-with-not
 (Bind
  (Not (Concept "X"))
  (Concept "Y")))

(cog-execute! evaluate-constant-pattern-with-not)
```
fails with error

`ERROR: In procedure cog-mandatory-args-fc: Not expecting a Node, here (ConceptNode "X")`

I think, since `(Not (Concept "X"))` is trivially present, the premise should evaluate to true.

**Comment by linas** [comment] 2017-12-22 15:02
You can use either `PresentLink` or `AbsentLink` -- the only valid arguments for `NotLink` are True, False, And Or. and nothing else.

**Comment by linas** [comment] 2017-12-22 22:38
OK, so I guess you will hate this - but Pull req #1500 adds a number of static type-checking routines that attempt to discover and prevent ill-formed expressions. In this case, it will prevent you from creating `(Not (Concept "X"))`    Please note, however, that `(Not (Predicate "X"))` is allowed.

I'm closing this as "user-error".

**Closed by linas** 2017-12-22 22:38 UTC

**Comment by Yidnekachew** [comment] 2017-12-25 08:25
@linas  I loved the error prevention thing. Why isn't `(Not (Not (Predicate "X")))` allowed then?

**Comment by ngeiswei** [comment] 2017-12-26 08:11
@Yidnekachew the problem is that in this context `NotLink` is interpreted as logic connector for the pattern matcher, as opposed to a literal atom that is part of the pattern. To tell the pattern matcher to interpret it as a literal you need to quote it, you may either use Quote or LocalQuote, for instance
```
Bind
  LocalQuote
    Not
      Concept "X"
  ...
```
See https://wiki.opencog.org/w/LocalQuoteLink

**Comment by Yidnekachew** [comment] 2017-12-26 08:27
An atom of the form `(Not (Concept "X"))` is invalid. Thus, I don't need a rule with it as a premise. 

But, as @linas stated above, `(Not (Predicate "X"))` is possible. And, since `NotLink` is treated here as logical negation, I think, it should also be possible to use `(Not (Not (Predicate "X"))` (i.e `~(~(X))`) which is double negation.

That isn't currently possible. I'm asking why.

**Comment by Yidnekachew** [comment] 2017-12-26 09:17
Yeah! Since the atom the I want to match is `(Not (Not (Predicate "X"))` I can use a rule like:
```
Bind
	Quote
		Not
			Not
				Unquote
					Predicate "X"
```
