### ISSUE TITLE
AtomSpace too early dtored by guile

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#2159] opened 2019-05-07 09:10 UTC
## Overview

While using the pattern miner, guile prematurely dtors a temporary atomspace holding KB + results.

## How to reproduce

In the following example https://github.com/opencog/opencog/tree/master/examples/learning/miner/sumo here's what seems to happened (best use commit
https://github.com/opencog/opencog/commit/6474595b631348d7f895eed0b52a05eec6f6fe62 to guaranty reproducibility):

1. Current atomspace is `parent-as`
2. Create `tmp-as` as child of `parent-as` https://github.com/opencog/opencog/blob/6474595b631348d7f895eed0b52a05eec6f6fe62/opencog/learning/miner/miner-utils.scm#L492
3. Set `tmp-as` as current atomspace https://github.com/opencog/opencog/blob/6474595b631348d7f895eed0b52a05eec6f6fe62/opencog/learning/miner/miner-utils.scm#L493
4. Create a list of atoms as corpus to mine in `tmp-as`
5. Miner `tmp-as` and put results in `tmp-as`
6. Set `parent-as` as current atomspace https://github.com/opencog/opencog/blob/6474595b631348d7f895eed0b52a05eec6f6fe62/opencog/learning/miner/miner-utils.scm#L533
7. Guile considers `tmp-as` is no longer useful and deletes it, as a result most results turn into invalid atoms.

If https://github.com/opencog/atomspace/blob/af9395ab81b57c2a03a836bc0cbeecb5fdcc07a3/opencog/guile/SchemeSmobGC.cc#L63 is commented out the bug goes away.

**Comment by ngeiswei** [comment] 2019-05-07 09:12
Certainly there must be a way to simply the test case to reproduce the bug, but I'm leaving that for later as it is not current the highest task on my list.

**Comment by linas** [comment] 2019-05-09 17:24
Umm, "working as designed" aka "not a bug"? Since the symbol `tmp-as` is never referenced again, it is impossible to access anything in the `tmp-as` -- that atomspace is dead to the world, and so can be safely deleted. 

I presume you made C++ lists/sets/arrays of the atoms that you found, and/or scheme lists. As long as   you have C++ Handle's to the atoms, those Handles will continue to point at valid atoms; but those atoms will not belong to any atomspace (the atomsapce pointer will be null).  If you have scheme lists holding atoms, then those atoms should still be there. If you have neither, then the atoms will go "poof" and be garbage-collected, since nothing can ever possibly access them, from either C++ or guile.

What is the actual bug? What actually happens?

**Comment by linas** [comment] 2019-05-09 17:30
If you want to hold onto `tmp-as` "forever", stick it in a global variable.

Also, instead of lines 492, 493, try using `(cog-push-atomspace)` and at lin 533, use `(cog-pop-atomspace)` These two create the temporary that you want.  The comments at line 534 and line 548 are non-sense ... you cannot delete something which doesn't exist.

**Comment by linas** [comment] 2019-05-09 17:32
ohhhh ... I see the problem, I see why you are getting the bug. I believe that using cog-push and cog-pop will fix it for you, because that will keep the temp atomspace in a global variable, until it is popped. Because it is in a global, it will not be prematurely deleted.

**Comment by linas** [comment] 2019-05-09 17:39
Note, however, the push-n-pop only push to a single global stack of atomspaces, If you need a per-thread stack, then, well, that can be done too; per-thread storage in guile are called "fluids" and we can add a parameter to push-pop for that. As long as the user is careful to define it correctly, so that it does not get garbage-collected prematurely.

**Comment by linas** [comment] 2019-05-09 17:55
Here: https://github.com/opencog/atomspace/blob/master/opencog/scm/opencog/base/utilities.scm#L985-L1018

**Comment by linas** [comment] 2019-05-09 18:04
I believe that opencog/opencog#3490 will fix this.

**Comment by linas** [comment] 2019-05-11 18:38
Closing this bug, since, as far as I can tell, ther's no actual bug in the atomspace code.  The general claim is this:

The atomspace was being deleted because there were no remaining references to it. This is a general property of  how any garbage-collected or reference-counted language or library deals with any reference. Whenever there's some object, and there are no remaining references to it, it is fair game for finalization.

In this case, the `miner-utils.scm` created a reference, but let it expire immediately, and so that reference was garbage-collected at some random point after the `cog-set-atomsapce!` call.

**Closed** 2019-05-11 18:46 UTC
Labels: bug, scheme
