### ISSUE TITLE
ubuntu 14.04 build fails due to gmp.h include

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1506] opened 2017-12-25 21:06 UTC
lack of gmp.h was a previous build failure fixed with package libgmp3-dev.  looks like it's ultimately required by guile 2.2 as installed by `octool -g`...

```
[ 82%] Building CXX object opencog/rule-engine/CMakeFiles/ruleengine.dir/URECommons.cc.o
In file included from /usr/include/x86_64-linux-gnu/gmp.h:51:0,
                 from /usr/local/include/guile/2.2/libguile.h:25,
                 from /home/cog/opencog/atomspace/opencog/guile/SchemeSmob.h:20,
                 from /home/cog/opencog/atomspace/opencog/rule-engine/URECommons.cc:25:
/usr/include/c++/4.9/cstddef:51:11: error: ‘::max_align_t’ has not been declared
   using ::max_align_t;
           ^
make[2]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/URECommons.cc.o] Error 1
make[1]: *** [opencog/rule-engine/CMakeFiles/ruleengine.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by linas** [comment] 2017-12-25 22:06
Try adding `#include <cstddef>` to URECommons.cc  above the guile include.

http://en.cppreference.com/w/cpp/types/max_align_t

**Comment by mjsduncan** [comment] 2017-12-26 18:29
that worked, thx.  should i push this fix?

**Comment by mjsduncan** [comment] 2017-12-26 22:10
also needed for opencog/nlp/fuzzy/FuzzySCM.cc (in opencog not atomspace repo)

**Comment by ngeiswei** [comment] 2018-01-03 05:00
@mjsduncan I'm not sure this code is still in use, let me take care of it, thanks.

**Comment by ngeiswei** [comment] 2018-01-03 17:15
@mjsduncan #1508 should fix the error for URECommons.cc (without having to add the extra include). I prefer to let you fix the other(s) as I can't reproduce them.

**Comment by linas** [comment] 2018-01-25 20:20
closing, since the discussion above suggests that it is fixed.

**Closed by linas** 2018-01-25 20:20 UTC
