### ISSUE TITLE
cygwin can't find cogutils

### ISSUE THREAD

**Issue by chris-hawley** [opencog/atomspace#781] opened 2016-05-12 21:40 UTC
i wasnt sure whether to post this issue in cogutils or atomspace. Below is the output of cmake. 

-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
-- Build type: Release
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105800 found.
-- Looking for include file opencog/util/cogutil.h
-- Looking for include file opencog/util/cogutil.h - found
-- CogUtil not found
CMake Error at CMakeLists.txt:195 (MESSAGE):
  CogUtil missing: it is needed for everything!

everything in cogutils built correctly so im not sure what the problem is.

**Comment by ngeiswei** [comment] 2016-05-13 03:57
It's the right place to post. Unfortunately I have no idea what the problem is, I haven't touched Cygwin for many years.

**Comment by chris-hawley** [comment] 2016-05-13 04:28
the part that confuses me the most about diagnosing the problem is that fact that it finds the header files.

**Comment by ngeiswei** [comment] 2016-05-13 05:39
Well, I've had this kind of problems under linux multiple times, usually it gets solved by running ldconfig. For Cygwin I have no idea.

**Comment by chris-hawley** [comment] 2016-05-13 13:31
from my brief research into what ldconfig does, ldconfig is equivalent of adding things to path. If you knew what variable is uses to look up cogutil, i can add the dll to path.

**Comment by chris-hawley** [comment] 2016-05-13 15:12
I fixed the problem. cygcogutil.dll and libcogutil.dll.a needed to be copied to usr\local\include\opencog
originally they were in the usr/local/bin/opencog folder

**Comment by ngeiswei** [comment] 2016-05-18 01:13
That's weird, isn't it? But anyway, if that fixes the problem... Would be good to have this information somewhere, on the wiki or perhaps a README.cygwin or something.

**Comment by chris-hawley** [comment] 2016-05-18 01:31
it was made that way by someone earlier. this is really a cogutils problem. However, i havent gotten a response on that project yet.  
https://github.com/opencog/cogutils/issues/32

**Comment by linas** [comment] 2016-06-28 19:18
Closing, this seems to be a duplicate of opencog/cogutils#32 

Chris, if you have access to a Windows box, and know how Cygwin works, then please do perform the port and submit pull requests.  None of the regular developers have access to a Windows machine or have any experience with Windows (except for YantraBuddhi who was an actual Windows developer once upon a time). 

From the strategic perspective, I think an Android port would be far more interesting: it would be very cool to run opencog on a cellphone/tablet.  (I don't have an iPhone, else I would be excited by that).

**Comment by chris-hawley** [comment] 2016-06-28 19:22
If I can port to windows, then I can use several specialized tools at performing these conversions. I will need help modifying the Cygwin part of the make file. Can you make the change I noted above?

**Comment by linas** [comment] 2016-06-28 19:24
Note, however, such a port would be hard: opencog requires scheme, python and postgres.  Its not clear that any of these are fully functional and supported on windows, cygwin or android or OSX.  I recall asking about scheme-on-android, and someone had tried it and gotten it to sort-of mostly work, but the patches for doing that are not upstream, as far as I know.  Getting all of these pre-reqs to work happily on non-Linux systems is not a weekend project: it would require a fair bit of dedication.

**Comment by linas** [comment] 2016-06-28 19:28
Hi Chris ... what change?  Submit a pull request ... if it looks good, it can be merged.  It seems like the first step is to port cogutils to cygwin, and have that work and pass it's unit tests. once that works, then we can close issue opencog/cogutils#32  and re-open this one (or create a new issue that says "port atomspace to cygwin")

**Comment by chris-hawley** [comment] 2016-06-28 23:56
i will run unit tests on cogutils. the DLL was copied to the wrong directory during install. 

copied from above: 

> cygcogutil.dll and libcogutil.dll.a needed to be copied to usr\local\include\opencog. originally they were in the usr/local/bin/opencog folder

**Comment by chris-hawley** [comment] 2016-06-29 01:15
To get cogutils to build from on cygwin. note: these directions do not include installing dependencies 

1. clone repository
2. go through make process as normal
3. during installation('make install') cygcogutil.dll and libcogutil.dll.a are installed under 'usr\local\include\opencog' . move them to usr/local/bin/opencog. (this step needs to remedied via an update cmake file)
4. for tests, download cxxtest and extract anywhere. go into that folder and copy cxxtest to /usr/local/include. 'make test' should succeed after that. 

all tests succeeded. moving on to atomspace.

**Comment by linas** [comment] 2016-06-29 02:02
OK, re-opening to track the work.  Please submit a pull request to cogutils that fixes all the issues that you had to manually work around.  Make sure that libraries are installed in `lib` and not in either `include` nor in `bin`

**Comment by linas** [comment] 2016-08-13 02:22
closing. There was no pull request made, or maybe there was, but this bug was never updated.

**Closed by linas** 2016-08-13 02:22 UTC
Labels: duplicate, enhancement
