### ISSUE TITLE
Strange behavior when doing pattern matching with ImplicationLink

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#1576] opened 2018-02-12 09:38 UTC
To reproduce it:

```scm
(use-modules (opencog) (opencog exec))

;  It may not make sense but it's used to demonstrate the issue
(define impl
  (ImplicationLink
    (AndLink
      (EvaluationLink
        (PredicateNode "some-pred")
        (ListLink
          (VariableNode "$x")
        )
      )
      (TrueLink)
    )
    (ConceptNode "goal")
  )
)

; Link with an anchor
(StateLink (AnchorNode "A") impl)

; PM query
(define sat
  (SatisfactionLink
    (TypedVariable
      (VariableNode "$y")
      (TypeNode "ImplicationLink")
    )
    (AndLink
      (StateLink (AnchorNode "A") (VariableNode "$y"))
    )
  )
)

(cog-evaluate! sat)
```

I would expect the evaluation to be true but it turns out to be false. On the other hand if I replace the above `StateLinks` with `ListLinks`, it returns true...

**Comment by leungmanhin** [comment] 2018-02-12 09:49
Also if I replace `(VariableNode "$x")` with any type of node that is not a variable, or type that variable, it will return true as well. So is a free variable causing this problem?

**Comment by ngeiswei** [comment] 2018-02-12 15:07
Can you try to replace `ImplicationLink` by `ImplicationScopeLink`?

**Comment by leungmanhin** [comment] 2018-02-13 03:45
Yes `ImplicationScopeLink` works. I'm wondering why does the scope matter in this case?

**Comment by ngeiswei** [comment] 2018-02-13 05:44
I suppose what happens is that `SatisfactionLink` finds the match (the implication), runs it, finds a variable in it and include it to the satisfaction problem. The `ImplicationScope` hides the variable, x, from the `SatisfactionLink` so the problem doesn't occur.

Regardless of whether it is or not a wanted behavior of `SatisfactionLink`, it `ImplicationScope` is really what you want to use, if you carefully read https://wiki.opencog.org/w/ImplicationScopeLink you'll probably understand why, please let me not otherwise.

**Comment by leungmanhin** [comment] 2018-02-13 06:36
It seems to be the case... though why would it be included in the satisfaction problem, I think `ImplicationLink` is declarative?

**Comment by ngeiswei** [comment] 2018-02-13 07:13
I would agree [that it's an unwanted behavior], maybe @linas can shine a light on it.

**Comment by linas** [comment] 2018-02-14 06:31
I was going to look at this today, but I didn't. Maybe tomorrow? Is this urgent?

**Comment by leungmanhin** [comment] 2018-02-14 06:34
It's not urgent, thanks @linas!

**Comment by linas** [comment] 2019-05-22 02:54
I finally looked at this. In the narrow scheme of things, this is a user-error, not a bug, its working-as-designed.  Although I do have a patch that will make the pattern matcher more tolerant (and still pass unit tests).

So: The "problem" is that StateLink is designed to hold  State, and state is always assumed to be "closed" (i.e. to not have free variables in it.)  That is, StateLink can only have one-and-at-most-one closed state. Anything else containing variables is assumed to be some part of some other search pattern and is thus ignored.  Thus, you can't actually use StateLink as above - its illegal.  

Nil is right; the ImplicationScopeLink hides the free variable; the State now appears to be closed, and thus a valid state.

I'm gonna close this bug, but first, I'll add a unit test to check-for and force this behavior (because it should not get "fixed" some other future day, incorrectly.

**Comment by linas** [comment] 2019-05-22 03:20
Closing. Pull req #2177 tightens the unit test to confirm this behavior as expected behavior.

**Closed by linas** 2019-05-22 03:20 UTC
Labels: pattern-matcher

**Comment by leungmanhin** [comment] 2019-05-22 07:14
OK, thanks for the clarification!
