### ISSUE TITLE
Cygwin fails to link cygtruthvalue.dll

### ISSUE THREAD

**Issue by chris-hawley** [opencog/atomspace#782] opened 2016-05-13 15:52 UTC
[  5%] Linking CXX shared library cygtruthvalue.dll
lto1: warning: -fPIC ignored for target (all code is position independent)
lto1: warning: -fPIC ignored for target (all code is position independent)
lto1: warning: -fPIC ignored for target (all code is position independent)
lto1: warning: -fPIC ignored for target (all code is position independent)
lto1: warning: -fPIC ignored for target (all code is position independent)
lto1: warning: -fPIC ignored for target (all code is position independent)
lto1: warning: -fPIC ignored for target (all code is position independent)
Cannot export _ZNSt12__shared_ptrIN7opencog14NullTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog15CountTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKS1_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog15CountTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRfS7_RdEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog15FuzzyTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKS1_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog16SimpleTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKS1_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog16SimpleTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKffEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog16SimpleTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRdRfEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog16SimpleTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIddEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog16SimpleTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIffEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog17GenericTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKS1_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog17GenericTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRdS7_S7_RfS7_S7_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog20IndefiniteTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKS1_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog23ProbabilisticTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRKS1_EEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt12__shared_ptrIN7opencog23ProbabilisticTruthValueELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EIRfS7_RdEEESt19_Sp_make_shared_tagRKT_DpOT0_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog14NullTruthValueESaIS5_EIEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog15CountTruthValueESaIS5_EIRKS5_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog15CountTruthValueESaIS5_EIRfS7_RdEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog15FuzzyTruthValueESaIS5_EIRKS5_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog16SimpleTruthValueESaIS5_EIRKS5_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog16SimpleTruthValueESaIS5_EIRKffEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog16SimpleTruthValueESaIS5_EIRdRfEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog16SimpleTruthValueESaIS5_EIddEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog16SimpleTruthValueESaIS5_EIffEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog17GenericTruthValueESaIS5_EIRKS5_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog17GenericTruthValueESaIS5_EIRdS7_S7_RfS7_S7_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog20IndefiniteTruthValueESaIS5_EIRKS5_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog23ProbabilisticTruthValueESaIS5_EIRKS5_EEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
Cannot export _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN7opencog23ProbabilisticTruthValueESaIS5_EIRfS7_RdEEESt19_Sp_make_shared_tagPT_RKT0_DpOT1_: symbol wrong type (4 vs 3)
collect2: error: ld returned 1 exit status
opencog/truthvalue/CMakeFiles/truthvalue.dir/build.make:303: recipe for target 'opencog/truthvalue/cygtruthvalue.dll' failed
make[2]: *** [opencog/truthvalue/cygtruthvalue.dll] Error 1
CMakeFiles/Makefile2:1529: recipe for target 'opencog/truthvalue/CMakeFiles/truthvalue.dir/all' failed
make[1]: *** [opencog/truthvalue/CMakeFiles/truthvalue.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chris-hawley** [comment] 2016-06-02 02:36
any thoughts?

**Comment by linas** [comment] 2016-06-28 19:42
https://www.google.com/search?q=Cannot+export+symbol+wrong+type+(4+vs+3)

**Comment by linas** [comment] 2016-06-28 19:44
Seems to be covered by the umbrelled bug #781 and really opencog/cogutils#32  so closing as a duplicate of those.

**Closed by linas** 2016-06-28 19:44 UTC
