### ISSUE TITLE
How to make a choice while mapping in atomese?

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#644] opened 2016-02-15 12:06 UTC
When using a GetLink the returned result pattern could be variable. What I wanted to do is deal with each result depending on what the result of the get could be. In other words, how to do an `if-elif-else` pattern?
## Scheme functions

``` scheme
(define (rand-set)
    ; This is for simulating a return from a GetLink

    (define pseudo-get
        (RandomChoice
            (SetLink
                (SetLink (ListLink (ConceptNode "foo")))
                (SetLink
                    (ListLink
                        (ConceptNode "bar")
                        (NumberNode 1)))
            ))
    )

    (cog-execute! pseudo-get)
)

(define (map-test a-set)
    (define map-link
        (MapLink
            (ImplicationLink
                (VariableList
                    (TypedVariable (Variable "$x") (Type "ConceptNode"))
                    (TypedVariable (Variable "$y") (Type "NumberNode")))
                (ChoiceLink
                    (ListLink
                        (Variable "$x")
                        (Variable "$y"))
                    (ListLink
                        (Variable "$x"))
                )
                (Variable "$x")
            )
            a-set
        ))
        (display "The set = \n")
        (display a-set)
        (display "The mapping = \n")
        (cog-execute! map-link)
)
```
## Present Output

``` scheme
guile> (map-test (rand-set))
The set =
(SetLink
   (ListLink
      (ConceptNode "foo")
   )
)
The mapping =
(SetLink
)

guile> (map-test (rand-set))
The set =
(SetLink
   (ListLink
      (ConceptNode "bar")
      (NumberNode "1.000000")
   )
)
The mapping =
(SetLink
)

```
## Expected Output

``` scheme
guile> (map-test (rand-set))
The set =
(SetLink
   (ListLink
      (ConceptNode "foo")
   )
)
The mapping =
(SetLink
      (ConceptNode "foo")
)

guile> (map-test (rand-set))
The set =
(SetLink
   (ListLink
      (ConceptNode "bar")
      (NumberNode "1.000000")
   )
)
The mapping =
(SetLink
      (ConceptNode "bar")
)

```

**Comment by linas** [comment] 2016-02-15 16:38
Sounds like a bug to me.  Or rather, a missing feature; the code doesn't know or care about ChoiceLink.

However, you might be able to achieve the same thing with TypeChoice.  Let me try ...

**Comment by linas** [comment] 2016-02-15 18:43
Pull request #645 fixes this.  merge whenever it finishes doing its thing

**Comment by AmeBel** [comment] 2016-02-16 03:08
thanks

**Comment by AmeBel** [comment] 2016-02-16 03:27
I think I found a related buglet.

Modifying the `map-test` function above to use a `LambdaLink` as follows
```scheme
(define (map-test a-set)
    (define map-link
        (MapLink
            (LambdaLink
                (VariableList
                    (TypedVariable (Variable "$x") (Type "ConceptNode"))
                    (TypedVariable (Variable "$y") (Type "NumberNode")))
                (ChoiceLink
                    (ListLink
                        (Variable "$x")
                        (Variable "$y"))
                    (ListLink
                        (Variable "$x"))
                )
            )
            a-set
        ))
        (display "The set = \n")
        (display a-set)
        (display "The mapping = \n")
        (cog-execute! map-link)
)
```
and running it, I get
```scheme
guile>  (map-test (rand-set))            
The set =                                
(SetLink                                 
   (ListLink                             
      (ConceptNode "foo")                
   )                                     
)                                        
The mapping =                            
(SetLink                                 
)                                        
                                         
guile>  (map-test (rand-set))            
The set =                                
(SetLink                                 
   (ListLink                             
      (ConceptNode "bar")                
      (NumberNode "1.000000")            
   )                                     
)                                        
The mapping =                            
(SetLink                                 
   (ListLink                             
      (ConceptNode "bar")                
      (NumberNode "1.000000")            
   )                                     
)                                        
```
It seems to be half working,

## Expected output for one of the cases
```scheme
guile>  (map-test (rand-set))            
The set =                                
(SetLink                                 
   (ListLink                             
      (ConceptNode "foo")                
   )                                     
)                                        
The mapping =                            
(SetLink                                 
   (ListLink                             
      (ConceptNode "foo")                
   )                                     
) 
```

**Comment by linas** [comment] 2016-02-16 03:45
Looking.  You may want to create a unit test or extend the existing unit test for this.

**Comment by linas** [comment] 2016-02-16 03:54
Oh, the "related buglet" is actually due to ill-defined behavior.  The specification says that there are two variables: $x and $y.  For one of the cases, there is no grounding for $y.   So technically, that's a failed match.

I hit this earlier, and took the following approach: since $y is never actually used in the ImplicationLink, we can ignore the fact that it's ungrounded. So I hacked the code to skip the check for grounding $y in this case.  But now, you expose this issue, in a naked way that can no longer be hidden.

Your "Expected output" proposed that failed groundings should be ignored, but that is a weird and dangerous precedent, if implemented naively.   So, the correct implementation seems to be: if the selected choice does not have that variable in it, then its OK to leave it ungrounded.  That is easy to say, but might be harder to do. Pondering now...

**Comment by linas** [comment] 2016-02-16 03:57
Here is the buglet: https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/MapLink.cc#L243

**Comment by linas** [comment] 2016-02-16 04:13
We could just remove lines 243-245, and that would solve the buglet.  That seems like a mostly-safe thing to do, but it seems like it opens the door to other weird/unexpected behaviors.  Althought I can't think of any right now, cause I'm tired. Maybe there aren't any.  Not sure. 

You are welcome to comment out or remove lines 243-245, although maybe leave behind a note pointing out that this is a location for potential future strangeness. It smells like the kind of thing that @ngeiswei  will trip over in 6 or 12 months and then complain bitterly about how its done wrong.

Actually, @ngeiswei really should review and comment on this anyway, since the MapLink was something that he is responsible for inventing (or at least, needling me about it until it exceeded my pain threshold, whereupon I had to act.  I write code to (a) avoid pain (b) avoid the embarassment of being perceived as stupid.  I can't tell you how much energy I've devoted to convincing the world I'm not stupid; its more or less ruined my life.),

**Comment by bgoertzel** [comment] 2016-02-16 04:20
Somewhat peripherally, this thread reminded me that it would be good to have an IfElseLink ...

**Comment by AmeBel** [comment] 2016-02-16 04:32
I am trying to figure out the proper idiom for porting some scheme code to atomese. Lot of new behaviors had been added in the last couple of months, that I am catching up on. 

I can use the following to get my expected output
```scheme
(define (map-test a-set)
    (define map-link
        (MapLink
            (LambdaLink
                (TypedVariable
                    (Variable "$x")
                    (TypeChoice
                        (SignatureLink
                            (ListLink
                                (Type "ConceptNode")
                                (Type "NumberNode")))
                        (SignatureLink
                            (ListLink
                                (Type "ConceptNode")))
                    ))
                (Variable "$x")
            )
            a-set
        ))
        (display "The set = \n")
        (display a-set)
        (display "The mapping = \n")
        (cog-execute! map-link)
)
```
I don't know what should be the preferred way. There seems to be an intersection between typing and the terms.

**Comment by linas** [comment] 2016-02-16 04:38
Eh, @bgoertzel  I want to resist that. For two reasons:

1) There already is some way to do the equivalent of an IfElseLink, although it is too late at night for me to recall just how.  It should be explained, demoed, documented.

2) I feel like we've walked too far down the path of turning atomese into a procedural programming language.  We don't really need that.  We should return to our "roots": a declarative, probabilistic language.

In particular, we are much much to far away from probability these days: almost everything we do is crisp-logic, and, for that, atomese is not a strong contender.  Anyway, this bug report is an off-topic place to discuss this,

**Comment by linas** [comment] 2016-02-16 04:48
@AmeBel  There is no "preferred" way, at least, not for this. It depends on what you want to do.

Regarding the porting of scheme to atomese: why are you doing this?  Is it for an important reason, or because it feels fun?   The goal of doing anything in atomese is to:

1) Allow dynamic, run-time editing of graph structures.  For example: the rule-engine.

2) Allow dynamic, run-time creation of structures: e.g. moses creates new structures by learning.

3) Allow dynamic, run-time conversion of sensory inputs into structures e.g. the import of parsed sentences.

So, the goal should be that we write code in python, scheme, haskell, c++, that can perform the most general possible manipulations on graph structures so that learning, perception, thinking is possible.   We should NOT be "programming" in atomese, not by hand.  (even though, de facto, we do this all the time, and I'm the prime offender.  I'm setting a bad example. Do as I say, not as I do.)

**Comment by AmeBel** [comment] 2016-02-16 05:05
`1` is the main reason presently.

**Comment by ngeiswei** [comment] 2016-02-16 06:31
I don't see a problem with removing

https://github.com/opencog/atomspace/blob/master/opencog/atoms/core/MapLink.cc#L243

**Comment by linas** [comment] 2017-12-22 22:16
New location is  https://github.com/opencog/atomspace/blob/master/opencog/atoms/execution/MapLink.cc#L351

**Comment by linas** [comment] 2019-02-02 04:33
Closing; this was a question; I don't see any concrete action items here.

**Closed by linas** 2019-02-02 04:33 UTC
Labels: bug, execution, question
