### ISSUE TITLE
make[2]: *** No rule to make target '/usr/lib/libpq.so', needed by 'opencog/persist/sql/multi-driver/libpersist-pg.so'. atomspace installation

### ISSUE THREAD

**Issue by hanimunir** [opencog/atomspace#2239] opened 2019-06-28 12:12 UTC
Facing this error while installing executing make install command

make[2]: *** No rule to make target '/usr/lib/libpq.so', needed by 'opencog/persist/sql/multi-driver/libpersist-pg.so'.  Stop.
CMakeFiles/Makefile2:1581: recipe for target 'opencog/persist/sql/multi-driver/CMakeFiles/persist-pg.dir/all' failed
make[1]: *** [opencog/persist/sql/multi-driver/CMakeFiles/persist-pg.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by linas** [comment] 2019-06-28 17:45
closing duplicate of #2237

**Closed by linas** 2019-06-28 17:45 UTC
