### ISSUE TITLE
Circular dependencies in shared libraries

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace#1673] opened 2018-05-11 19:48 UTC
what could be causing this?
```
In FreeLinkUTest::test_getlink:
/home/mozi/oc/atomspace/build/tests/atoms/../../../tests/atoms/FreeLinkUTest.cxxtest:214: Error: Expected (vars.size() == 2), found (6 != 2)
/home/mozi/oc/atomspace/build/tests/atoms/../../../tests/atoms/FreeLinkUTest.cxxtest:216: Error: Expected (vars[1] == vz), found ({ 50 6D F2 2E 71 55 00 00 ... } != { B0 75 F2 2E 71 55 00 00 ... })
[2018-05-11 19:14:48:360] [DEBUG] END TEST: test_getlink
Failed 1 and Skipped 0 of 4 tests
```

**Comment by linas** [comment] 2018-05-11 22:20
Its one of those tests that never fails; thus, the most likely cause is some version skew: the libraries it is linke to are too old, are different, were build on a different system.  before running tests, do a `make install`.  to avoid having root ownership of files in your build directory, be sure you say `make` before saying `make install`.  If you have files owned by root, then `make` will fail to replace them by the newer (and correct) versions, thus leading to mystery unit test fails. If unsure, do an `rm -r *; cmake ..; make -j; sudo make install; make -j test`

**Comment by mjsduncan** [comment] 2018-05-11 22:38
already did that, it's happening on ubuntu 17.10 and ubuntu 16.04 after your test overhaul.

**Comment by linas** [comment] 2018-05-11 22:54
Hmm. None of the code that I touched would affect this unit test, or any unit tests aside from the atomspace, in any way. There were some recent updates to cogutils; that might(??) explain incompatible shared libs.

**Comment by mjsduncan** [comment] 2018-05-11 23:37
so to be clear, on what versions of ubuntu is this passing for you?

**Comment by linas** [comment] 2018-05-12 04:00
I'm running Debian stable. I have a hard time believing that this is OS related.perhaps @ngeiswei can provide a data point.

**Comment by linas** [comment] 2018-05-12 04:01
Debugging info: what does `ldd -r ./tests/atoms/FreeLinkUTest` display?

**Comment by mjsduncan** [comment] 2018-05-12 06:42
$ ldd -r ./tests/atoms/FreeLinkUTest
	linux-vdso.so.1 =>  (0x00007fff831f8000)
	libsmob.so => /home/cog/opencog/atomspace/build/opencog/guile/libsmob.so (0x00007f2ebc9a7000)
	libatomspace.so => /home/cog/opencog/atomspace/build/opencog/atomspace/libatomspace.so (0x00007f2ebc781000)
	libatomcore.so => /home/cog/opencog/atomspace/build/opencog/atoms/core/libatomcore.so (0x00007f2ebc502000)
	libatombase.so => /home/cog/opencog/atomspace/build/opencog/atoms/base/libatombase.so (0x00007f2ebc2cb000)
	libcogutil.so => /usr/local/lib/libcogutil.so (0x00007f2ebc07c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2ebbcfa000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2ebbae3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2ebb719000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2ebb4fc000)
	libguile-2.2.so.1 => /usr/local/lib/libguile-2.2.so.1 (0x00007f2ebb1ce000)
	libatomutils.so => /home/cog/opencog/atomspace/build/opencog/atomutils/libatomutils.so (0x00007f2ebafb0000)
	libtruthvalue.so => /home/cog/opencog/atomspace/build/opencog/truthvalue/libtruthvalue.so (0x00007f2ebad96000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2ebcbe0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2ebaa8d000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f2eba875000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f2eba671000)
	libbfd-2.26.1-system.so => /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so (0x00007f2eba32c000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f2eba0fd000)
	libgc.so.1 => /usr/lib/x86_64-linux-gnu/libgc.so.1 (0x00007f2eb9e8b000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f2eb9c83000)
	libunistring.so.0 => /usr/lib/x86_64-linux-gnu/libunistring.so.0 (0x00007f2eb996d000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f2eb96ed000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f2eb94e3000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f2eb92ab000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2eb9091000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2eb8e8d000)

**Comment by linas** [comment] 2018-05-12 16:56
Hmm. Well, that exposes several issues. Elsewhere, you were complaining about libboost-1.58, noting that it was too old (here: /opencog/opencog#3101) yet the too-old libboost is linked in here. So that's an issue.

In my executable, I have several libbooosts that you don't -- libboost_regex.so.1.62.0 and libboost_thread.so.1.62.0 - I don't know why, maybe it's nothing.

Next, you seems to be missing several libraries that I do have: viz. libclearbox.so and liblambda.so - this is subtle but important: those libraries contain constructors that must run, since they define factories for the classserver. Without the factories, the correct atom types will not get created. This is worrisome; I can't say that this is the root cause of the failure, but its not good. 

Its possible that your linker/loader has decided that it does not need to link these libraries. That would be a bug.  I'm investigating a bit more deeply now.

Are you sure you did a clean build? The stale libboost seems suspicious to me.

**Comment by linas** [comment] 2018-05-12 17:28
The only reason I can think that your libraries differ is because your gcc is passing in the `as-needed` flag. Some versions of gcc do this. To make sute that this is avoided, I added the `--no-as-needed` flag, just now, to one of the makefiles. Try a git pull and rebuild.

**Comment by mjsduncan** [comment] 2018-05-12 17:30
this dump is from my ubuntu 16.04 box that has libboost v1.58, i removed the old self installed cpprest from my ubuntu 18.04 box (which was done following the then current README, ldd output below) which is failing the unit tests in the same way. maybe i fucked both of them up somehow, but admit you actually have no idea whether the current build works on ubuntu ;)

```
ldd -r ./tests/atoms/FreeLinkUTest
	linux-vdso.so.1 (0x00007ffd4f381000)
	libsmob.so => /home/mozi/oc/atomspace/build/opencog/guile/libsmob.so (0x00007fa856ad1000)
	libatomspace.so => /home/mozi/oc/atomspace/build/opencog/atomspace/libatomspace.so (0x00007fa8568ac000)
	libatomcore.so => /home/mozi/oc/atomspace/build/opencog/atoms/core/libatomcore.so (0x00007fa85662c000)
	libatombase.so => /home/mozi/oc/atomspace/build/opencog/atoms/base/libatombase.so (0x00007fa8563f4000)
	libcogutil.so => /usr/local/lib/libcogutil.so (0x00007fa8561a1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa855e13000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa855bfb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa85580a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa8555eb000)
	libguile-2.2.so.1 => /usr/lib/x86_64-linux-gnu/libguile-2.2.so.1 (0x00007fa8552cf000)
	libatomutils.so => /home/mozi/oc/atomspace/build/opencog/atomutils/libatomutils.so (0x00007fa8550b0000)
	libtruthvalue.so => /home/mozi/oc/atomspace/build/opencog/truthvalue/libtruthvalue.so (0x00007fa854e96000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa856f29000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa854af8000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007fa8548de000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007fa8546d9000)
	libbfd-2.30-system.so => /usr/lib/x86_64-linux-gnu/libbfd-2.30-system.so (0x00007fa854389000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fa854159000)
	libgc.so.1 => /usr/lib/x86_64-linux-gnu/libgc.so.1 (0x00007fa853ee7000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fa853cdf000)
	libunistring.so.2 => /usr/local/lib/libunistring.so.2 (0x00007fa853968000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fa8536e7000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fa8534dd000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fa8532a5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa853088000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa852e84000)
```

**Comment by mjsduncan** [comment] 2018-05-12 18:41
ok now i'm getting this on both boxes:
The following tests FAILED:
	 23 - PutLinkUTest (SEGFAULT)
	 25 - AlphaConvertUTest (Failed)
where  before there were about 5 more tests failing.

**Comment by linas** [comment] 2018-05-12 19:33
The PutLink failure is "normal", its a three-month-old bug that I have not found time to fix, because other things keep coming up. All other tests should be passing. Ask @konstantin-t - he's new, he might be able to figure out what's going on.

**Comment by konstantin-t** [comment] 2018-05-13 08:59
I will take a look. Actually there are roughly 10 failing tests in Master, and I planned to understand, how to fix that. I will start with tests 23 and 25 on Monday.

**Comment by konstantin-t** [comment] 2018-05-13 21:29
Maybe. It seems like the typical reason why the test fail in my environment is the following.

Consider PutLinkUTest::test_function. It thinks it creates a PlusLink. But in fact, ClassServer::getFactory(PLUS_LINK) returns a factory for FunctionLink. That happens because for some reason
```
static __attribute__ ((constructor)) void init(void) 
```
in PlusLink.cc is not executed.

Adding clearbox library to the CMakeList.txt, even forcibly, does not help:
```
	ADD_CXXTEST(PutLinkUTest)
	TARGET_LINK_LIBRARIES(PutLinkUTest -Wl,--whole-archive clearbox -Wl,--whole-archive execution smob atomspace)
```
The ldr still does not show the clearbox.

If I register the factory manually, the test passes
```
void PutLinkUTest::test_function()
{
+  classserver().addFactory(PLUS_LINK, &PlusLink::factory);
```

After writing this text, @linas, I noticed your comment: "This is worrisome; I can't say that this is the root cause of the failure, but its not good."

Seems like it is exactly this. I am using Ubuntu 17.10.
I will take a look at this issue tomorrow. Cheers!

**Comment by konstantin-t** [comment] 2018-05-13 21:34
And by the way, after I add the row which calls addFactory, it makes clearbox appear in the list of linked libraries.
Seems like linker becomes too clever.

**Comment by konstantin-t** [comment] 2018-05-13 21:40
Still some tests from PutLink fail. Though, I think now the reason is different.

**Comment by linas** [comment] 2018-05-13 21:40
Pull req #1676 fixes PutLinkUTest

**Comment by linas** [comment] 2018-05-13 22:15
> Seems like linker becomes too clever.

Ouch. yes, that would cause trouble. We need some way of forcing all constructors for all shared libraries to run, especially for the shared libraries that define atoms. This is actually hard to do, because there are some circular dependencies between the libraries in the atomspace, and fixing those circular dependencies is surprisingly hard.  (I've tried and failed several times)  The two worst offenders are these:

* ExecutionLink (an atom type) needs to link to python & guile, but python and guile need to link to the atomspace, which would be a natural place to run all shard lib ctors.

* PatternLink/BindLink (an atom type) needs to link to atompace, because it uses temporary atomspaces for speculative execution. But, again ...

Right now, the CMakefile specify a set of shared-lib dependencies that work (or have worked until now), but they're ad-hoc and kind-of incoherent.

**Comment by konstantin-t** [comment] 2018-05-14 12:36
I traced operations of Make, and learnt why ```--whole-archive``` parameter did not help. It looks like Make identifies, that ```execution``` library (which is being linked to the test executable) already refers to ```clearbox```. As there is no need to link a lib twice, the declaration of ```clearbox``` between ```--whole-archive```/```--no-whole-archive``` was implicitly omitted. 

There is a hackish approach to fix the issue. One has to reference any method from ```clearbox``` in the code of ```execution```. Something like this:
```
void (*_)() __attribute__((unused)) = &opencog::foo;
```
Unfortunately, after I fast forwarded my local repository and rebuilt it, the issue disappeared. So I could not verify, that such hackish approach is reliable. Let's wait for this problem to re-appear.

**Comment by konstantin-t** [comment] 2018-05-15 20:50
Today I reproduced the same issue with AlphaConvert. The BindLink was not "initialized" in the class server. That made ```AlphaConvertUTest::test_bindlink``` fail in a very unusual way.

The remedy was to enforce linker to link against the required libraries using the following pattern:
```
-Wl,--no-as-needed lambda -Wl,--as-needed
```

Presently all tests on my machine succeed.

**Comment by konstantin-t** [comment] 2018-05-15 20:58
This is the full line:
```
TARGET_LINK_LIBRARIES(AlphaConvertUTest -Wl,--no-as-needed lambda -Wl,--as-needed atomspace)
```

The fix introduced by Nil and Linas works too.

**Comment by konstantin-t** [comment] 2018-05-15 21:09
As in fact the libraries clearbox, atomcore, execution and lambda needs to be linked, even if the linker thinks the opposite, I suppose we have to use ```--no-as-needed``` systematically in all CMakeLists.txt files. Otherwise there might be unexpected failures when someone eliminates usage of a class in the source code.

@nielsgl, @linas, what do you think?

**Comment by linas** [comment] 2018-05-16 02:23
Yes, we probably need `--no-as-needed` in all the library makefiles. Note that `${NO_AS_NEEDED}` is already defined, its meant to make porting to macos easier. Except who knows what bugs will lurk in MacOS.

**Comment by linas** [comment] 2018-05-16 21:45
So #1691 takes the core idea from #1690, and expands it to all of the libraries that have circular dependencies. It almost works, but not quite; there seem to be multiple issues. These are:
* Despite explicitly linking libraries with ctors in them to the libatomspace.so, it does not seem like the ctors will be called; but I can't quite tell.  I looked with `nm libatomspace.so` and it was not promissing, but its possible the ctors are invoked by `_init` in `ld.so` or some non-obvious way. I did not check by putting printfs into the ctors.
* `nm libsmob.so` shows that it is bizarrely empty; this is unexpected.
* The opencog repo does not build with #1691 applied.  I get this error:
```
/usr/bin/ld: CMakeFiles/patternIndexQueryExample.dir/patternIndexQueryExample.cc.o: undefined reference to symbol '_ZN7opencog10SchemeEval11init_schemeEv'
/usr/local/lib/opencog/libsmob_.so: error adding symbols: DSO missing from command line
```
which is also unexpected.

Can you treat #1691 as a sketch for an idea, that somehow is not quite right, and maybe figure that out, and fix it?

**Comment by konstantin-t** [comment] 2018-05-18 12:29
Here is a table showing dependencies. (check #1691)

![dependencies](https://user-images.githubusercontent.com/39221192/40234605-2687b8d6-5ab0-11e8-8dbd-87f5a1735f22.png)

**Comment by linas** [comment] 2019-02-02 16:42
Closing; most of the things discussed here have been fixed; and the conversation got side-tracked, anyway.

**Closed by linas** 2019-02-02 16:42 UTC

**Comment by linas** [comment] 2019-02-02 21:38
#2035 resolves most of the rest.
