### ISSUE TITLE
AlphaConvertUTest::test_bindlink fails

### ISSUE THREAD

**Issue by ngeiswei** [opencog/atomspace#1680] opened 2018-05-15 11:18 UTC
It fails when comparing
```
hscox = (BindLink
  (VariableNode "$X") ; [6809953386495729144][1]
  (PresentLink
    (VariableNode "$X") ; [6809953386495729144][1]
  ) ; [16058869277486449580][1]
  (AndLink
    (VariableNode "$X") ; [6809953386495729144][1]
  ) ; [16055386024649729858][1]
) ; [12487348734513047317][1]
```
and
```
hscoy = (BindLink
  (PresentLink
    (VariableNode "$X") ; [6809953386495729144][2]
  ) ; [16058869277486449580][2]
  (AndLink
    (VariableNode "$X") ; [6809953386495729144][2]
  ) ; [16055386024649729858][2]
) ; [16295387175712849125][2]
```
which to me points to a problem with `ScopeLink::compute_hash`. Probably surfaced only now due to some alteration in the hash.

**Comment by ngeiswei** [comment] 2018-05-15 11:41
The weird shit reason is that `_vardecl` is undefined for `hscox` while clearly there is a variable declaration.

**Comment by ngeiswei** [comment] 2018-05-15 12:13
The bug has been introduced either in baf7991ee or 47add8fa8 (I can't tell since 47add8fa8 doesn't compile).

**Comment by ngeiswei** [comment] 2018-05-15 12:30
For some reason, after these commits `BindLink::extract_variables` is no longer called, that's weird, it should utterly break everything.

**Comment by linas** [comment] 2018-05-16 02:27
Closing as a duplicate of #1673

**Closed by linas** 2018-05-16 02:27 UTC
