### ISSUE TITLE
Best way to find values in python

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/atomspace#2488] opened 2020-01-31 01:48 UTC
[The scheme values example](https://github.com/opencog/atomspace/blob/master/examples/pattern-matcher/value-of.scm) works great and shows us a way to set values to particular atoms and then find atoms that have particular values.
 
What would be the best way to reproduce it in python (that is, the python bindings for atomspace)?

The beginning looks simple enough: define nodes and keys:
```python
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog, finalize_opencog
from opencog.atomspace import AtomSpace, types
from opencog.bindlink import execute_atom, evaluate_atom
from opencog.scheme_wrapper import scheme_eval


atomspace = AtomSpace()
initialize_opencog(atomspace)

thing_a = ConceptNode("thing a")
thing_b = ConceptNode("thing b")

key = PredicateNode("some key")
```
then set the values:
```python
thing_a.set_value(key, FloatValue(42))
thing_b.set_value(key, FloatValue(35))
```

But what should the `BindLink` look like? 
```python
find_answer = BindLink(
				TypedVariableLink(
					VariableNode("$X"),
					TypeNode("ConceptNode")
					), 
				AndLink(
					PresentLink(
						VariableNode("$X"),
						GreaterThanLink(
							DivideLink(
								ValueOfLink(
									VariableNode("$X"),
									key),
								NumberNode("12")
								),
							NumberNode("3")
							)
						), 
				VariableNode("$X")
				)
				)
``` 
seems sort-of correct, but returns an empty `SetLink`.

**Comment by linas** [comment] 2020-01-31 03:16
I think you nested the `PresentLink` incorrectly. `Present` says "this stuff must be in the atomspace". You are NOT looking for the GreaterThan to be present; instead you just want to evaluate the greater-than and see if its true. 

So the following should work:
```
                  BindLink(
				TypedVariableLink(
					VariableNode("$X"),
					TypeNode("ConceptNode")
					), 
				AndLink(
					PresentLink(VariableNode("$X")),
					GreaterThanLink(
						DivideLink(
							ValueOfLink(
								VariableNode("$X"),
								key),
							NumberNode("12")
							)
						)
 					)
				)
				VariableNode("$X")
			)
		)
```

And you don't need the `Preesent(Variable(x))` because that is implicit, so this should be enough:
```
              BindLink(
				TypedVariableLink(
					VariableNode("$X"),
					TypeNode("ConceptNode")
					), 
				GreaterThanLink(
					DivideLink(
						ValueOfLink(
							VariableNode("$X"),
							key),
						NumberNode("12")
					)
 				)
			       VariableNode("$X")
		)
```

**Comment by StrangeTcy** [comment] 2020-02-10 11:51
Sorry, it has to be 
```
BindLink(
				TypedVariableLink(
					VariableNode("$X"),
					TypeNode("ConceptNode")
					), 
				GreaterThanLink(
					DivideLink(
						ValueOfLink(
							VariableNode("$X"),
							key),
						NumberNode("12")
					),
                                       NumberNode("3")
 				)
			       VariableNode("$X")
		)
```,
otherwise the `GreaterThanLink` wouldn't know what to compare the result of the `DivideLink` with. 
Otherwise it works as intended, thanks.

**Comment by linas** [comment] 2020-02-10 15:20
> Sorry, it has to be

Yes, absolutely right. I must have been cross-eyed.

> the best way to just find all the nodes in the atomspace that have any value associated with a particular key?

My knee-jerk reaction is that this is impossible, by design. The original intent was that if you want something to be findable, you must pay the price for it: you must make it an Atom ... Atoms are findable, because they live in an index, have an incoming set, etc. but these indexes, etc. have a cost, which Values don't have.  Values get rid of the cost, but as a result they're not searchable... that's the main difference.

That said, I suppose that one could, in principle, perform an exhaustive search of the atomspace, in some style similar to what you wrote.  Maybe we could invent some `HasAValueLink` or something like that. Or 'TypeOfValueLink`. That would work .. but at a different price: each and every single Atom would have to be examined to see if that key is present. So such a search would be possible .. but very slow.

Another possibility would be to alter the atomsspace design to create an index for each key ... but now, this becomes costly, since the index occupies RAM, and CPU cycles are needed to insert into that index. Which partly defeats the purpose of Values being simple, light-weight.  I'll have to think about that a bit.

What are you trying to do?  Is there a specific problem you want to solve?

**Comment by StrangeTcy** [comment] 2020-02-11 04:49
Well, without going into too much detail, let's just say I have a map. I create keys like `key1 = PredicateNode("longtitude")` and `key2 = PredicateNode("latitude")`, and then I use these keys to set a lot of values: `my_place = ConceptNode("my place"); my_place.set_value(key1, FloatValue(12.3456))`. Then, in another part of the whole thing, I get coordinates from a user and try to find a place that has the same coordinates as its values.

This particular problem can be solved by a `GetLink` or a `BindLink`, and doesn't really illustrate a need to find all atoms with specific values, but still.

**Comment by linas** [comment] 2020-02-11 07:34
Well, you could just say 
```
MemberLink(ConceptNode("my place"), ConceptNode("has-location"))
```
and then get the incoming set of `Concept("has-location")` -- better yet, call `get_incoming_set_by_type(Concept("has-location"), "MemberLink")` -- this will give you all atoms that .. have a location. And if you do it right, they will all have long & lat  values on them.

I'm not sure of the exact python syntax and function names, but that's the general idea. The "incoming set" is a very high-speed index for obtaining all links that contain some given atom. There's no need to run the pattern matcher, because the query is just too trivial.  As a general rule, for simple queries, its faster to just traverse the incoming/outgoing sets by hand, than to write a pattern.  As to which is easier, that depends.

**Comment by linas** [comment] 2020-02-11 07:36
... if you want to actually search geographical areas, well, the space-server is supposed to do that, but it is not maintained. Might need to be dusted off.

**Comment by linas** [comment] 2020-02-11 07:41
... also, it might be convenient to installed the lat/long keys and values not on the `Concept("my place")` but instead on the `MemberLink` ... it's a perfectly valid place to hang data, instead of cluttering up `Concept("my place")` with 500 keys & values.  Just an idea ...

**Comment by linas** [comment] 2020-03-27 20:54
Closing, this was a discussion, and I think everything was resolved. Please re-open if there's more to be discussed.

**Closed by linas** 2020-03-27 20:54 UTC
Labels: pattern-matcher, python, question
