### ISSUE TITLE
Garbage left in atomspace by executing AssignLink

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#58] opened 2015-05-24 09:27 UTC
@linas  if I understood https://github.com/opencog/atomspace/blob/master/opencog/atoms/reduct/AssignLink.h#L70 correctly, there shouldn't be a `(NumberNode "1.000000" (av 0 0 0))` in the atomspace.

```
guile> (clear)
guile> (define (counter)
    (define (increment-number str)  (+ (string->number str) 1))
     (let ((nn (cog-chase-link 'ReferenceLink 'NumberNode (AnchorNode "count"))) )
        (if (null? nn)
            (ReferenceLink
                (AnchorNode "count")
                (NumberNode 1)
                )
            (begin
                (cog-execute!
                    (AssignLink
                        (TypeNode "ReferenceLink")
                        (AnchorNode "count")
                        (NumberNode (increment-number (cog-name (car nn))))
                    )
                )
  
            )
        )
    )
)

guile> (define (ncount n)
    (while (not (= 0 n) ) (begin (set! n (- n 1)) (counter) )  )
)
guile> (ncount 5)
guile> (cog-prt-atomspace)
(ReferenceLink
   (AnchorNode "count")
   (NumberNode "5.000000" (av 0 0 0))
)
(AssignLink
   (TypeNode "ReferenceLink" (av 0 0 0))
   (AnchorNode "count")
   (NumberNode "5.000000" (av 0 0 0))
)
(AssignLink
   (TypeNode "ReferenceLink" (av 0 0 0))
   (AnchorNode "count")
   (NumberNode "4.000000" (av 0 0 0))
)
(AssignLink
   (TypeNode "ReferenceLink" (av 0 0 0))
   (AnchorNode "count")
   (NumberNode "3.000000" (av 0 0 0))
)
(AssignLink
   (TypeNode "ReferenceLink" (av 0 0 0))
   (AnchorNode "count")
   (NumberNode "2.000000" (av 0 0 0))
)
(NumberNode "1.000000" (av 0 0 0))

```

**Comment by linas** [comment] 2015-05-28 03:40
Several remarks:

1) The AssignLink does not remove either the NumberNode, nor does it remove the AnchorNode; it was not designed to remove either; it only removes the ReferenceLink.  Having it remove things is a potentially dangerous/incorrect thing to do.

2) I am working on implementing GetLink PutLink, which seems to be a better generalization. This may or may not result in AssignLink being re-implemented with get/put, or maybe having get/put somehow doing everything assign does now, and more.  It is still a little unclear. 

3) garbage collection is potentially a huge problem, not just for AssignLink, but for anything that uses cog-execute! and cog-evaluate!  The problem is that these often generate intermediate results, which are not cleaned up.  For example, anything that uses GroundedPredicatenode or GroundedSchemaNode must put the arguments into the atomspace: neither scheme nor python work right if the atoms are not in the atomspace. However, the temporary atoms that were created are (at this time) are not removed.  I might be able to partly clean this up.  its kind of confusing and difficult, at the moment.     

By the way: it is not really a scheme/python limitation: if for example, you want to get an accurate truth value for an atom, you MUST get it from the atomspace. Otherwise, you have some pointer to some atom which points to some TV, but who knows: PLN may have changed that TV, and you would never know, if you did not look in the atomspace.

**Comment by AmeBel** [comment] 2015-05-28 04:11
on 1) Well then the problem is we don't have NumberNodes for 2,3 & 4. I guess i will have to wait on how 2) turns out and check back on this.

**Comment by linas** [comment] 2015-05-28 04:50
!? but of course you have NumberNodes for 2,3,4: they are right there in your (cog-prt-atomspace) listing. What you don't have is an assign link wrapping number-node 1

**Comment by AmeBel** [comment] 2015-05-28 05:20
yap, missed that

**Comment by linas** [comment] 2015-12-27 03:04
Closing  ... AssignLink was removed a while ago.  There were also several bug fixes to avoid leaving garbage behind in atomspace, when stuff gets executed.

**Closed by linas** 2015-12-27 03:04 UTC
Labels: bug, pattern-matcher
