### ISSUE TITLE
Linker error when trying to add load_scm target as dependency

### ISSUE THREAD

**Issue by Habush** [opencog/atomspace#2674] opened 2020-06-04 17:20 UTC
I am working on a project that uses `fast_load.h` and in my cmake file I have the following `target_link_libraries` call:

```
TARGET_LINK_LIBRARIES(custom_lib
        ${COGUTIL_LIBRARIES}
        ${ATOMSPACE_atomtypes_LIBRARY}
        ${ATOMSPACE_atombase_LIBRARY}
        ${ATOMSPACE_atomcore_LIBRARY}
        ${ATOMSPACE_atomspace_LIBRARY}
        ${ATOMSPACE_value_LIBRARY}
        ${ATOMSPACE_truthvalue_LIBRARY}
        ${ATOMSPACE_load_scm_LIBRARY})
```

The linker finds all other atomspace libraries except `${ATOMSPACE_load_scm_LIBRARY}`. Why is that? and how can I fix it? I tried this in both linux and macOS.

**Comment by linas** [comment] 2020-06-04 20:26
It was never added to the list of libraries.  This is fixed in commit 54f969b 

I strongly recommend using `${ATOMSPACE_libraries}` instead of trying to specify them one-at-a-time.  The problem is that they have many circular dependencies between one-another, and its hard to figure out what's where. The `${ATOMSPACE_libraries}` gets all of them.

**Closed by linas** 2020-06-04 20:26 UTC
