### ISSUE TITLE
Failed to store atoms into postgres sometimes

### ISSUE THREAD

**Issue by leungmanhin** [opencog/atomspace#792] opened 2016-05-30 10:58 UTC
Sometimes I got errors when storing atoms into postgres. To reproduce it, assuming there is an empty database called "mycogdata" and we start the guile interpreter with an empty atomspace, then after doing:

```
(use-modules (opencog) (opencog persist-pgsql))

(List (Concept "A"))
(pgsql-open "mycogdata" "opencog_user" "cheese")
(pgsql-store)
(pgsql-close)

(clear)

(Set (Concept "A"))
(pgsql-open "mycogdata" "opencog_user" "cheese")
(pgsql-store)
```

I got:

```
scheme@(guile-user)> (pgsql-store)
  Max UUID is 6
Can't perform query rc=-1 (7) ERROR: duplicate key value violates unique constraint "atoms_type_name_key"
Key (type, name)=(7, A) already exists.;
Error while executing the query
    Query was: INSERT INTO Atoms (uuid, space, type, name, height, tv_type, stv_mean, stv_count, stv_confidence) VALUES (4, 1, 7, $ocp$A$ocp$, 0, 1,            1,            0,            0);
Can't perform query rc=-1 (7) ERROR: duplicate key value violates unique constraint "spaces_pkey"
Key (space)=(1) already exists.;
Error while executing the query
    Query was: INSERT INTO Spaces (space, parent) VALUES (1, 1);
Can't perform query rc=-1 (7) ERROR: duplicate key value violates unique constraint "atoms_type_name_key"
Key (type, name)=(7, A) already exists.;
Error while executing the query
    Query was: INSERT INTO Atoms (uuid, space, type, name, height, tv_type, stv_mean, stv_count, stv_confidence) VALUES (4, 1, 7, $ocp$A$ocp$, 0, 1,            1,            0,            0);
  Finished storing          2 atoms total.
$7 = ()
```

and the database was corrupted.

However, it's ok if I don't do `(pgsql-close)` before storing `(Set (Concept "A"))`:

```
(use-modules (opencog) (opencog persist-pgsql))

(List (Concept "A"))
(pgsql-open "mycogdata" "opencog_user" "cheese")
(pgsql-store)

(clear)

(Set (Concept "A"))
(pgsql-store)
```

It's also ok if I don't do `(clear)` before storing `(Set (Concept "A"))`:

```
(use-modules (opencog) (opencog persist-pgsql))

(List (Concept "A"))
(pgsql-open "mycogdata" "opencog_user" "cheese")
(pgsql-store)
(pgsql-close)

(Set (Concept "A"))
(pgsql-open "mycogdata" "opencog_user" "cheese")
(pgsql-store)
```

This may be a weird usage, but it would be nice if doesn't corrupt the database at least.

**Comment by jswiergo** [comment] 2016-05-31 14:42
I think in some situations atom storage failure is correct behavior. However if corrupted database is left after operation failure it is obviously wrong.

It is not allowed to store a node into database if another node with the same name and different uuid already exists in the database.

So in the described cases we got:
* Without execution of ```(clear)```, the node ```Concept "A"``` still got uuid=2, because the atomspace has not changed.
* Without execution of ```(pgsql-close)``` the connection to atom storage is still active, so when new node ```Concept "A"``` is created it is retrived from the database and got uuid=2 again.
* If both ```(clear)``` and ```(pgsql-close)``` are executed then new node ```Concept "A"``` may get any uuid. The node is no longer in the atomspace, there is no persistent storage connected. For example it gets uuid=4.

Because the last one seems to be a corner case but not a typical scenario (is it true?) it sounds reasonable that store operation fails in such situations. Otherwise we would have to unify and resolve conflicts between uuids in the current atomspace and atom storage. This would violate assumption that uuid is the immutabe key in the atomspace, so would be wrong.

However it is not correct to leave corrupted database after failure. After running the failing example above we got:
```
opencog_test=> select * from Atoms;
 uuid | space | type | tv_type | stv_mean | stv_confidence | stv_count | height | name |      out_hash       | out_differentiator | outgoing 
------+-------+------+---------+----------+----------------+-----------+--------+------+---------------------+--------------------+----------
    2 |     1 |    7 |       1 |        1 |              0 |         0 |      0 | A    |                     |                    | 
    3 |     1 |   12 |       1 |        1 |              0 |         0 |      1 |      |  258452015423105352 |                  0 | 
    5 |     1 |   11 |       1 |        1 |              0 |         0 |      1 |      | 1570194438561549153 |                  0 | 
(3 rows)

opencog_test=> select * from Edges;
 src_uuid | dst_uuid | pos 
----------+----------+-----
        3 |        2 |   0
        5 |        4 |   0
```
The Edge(5,4) is incorrect, because Atom(uuid=4) does not exit (is not inserted because of conflict). As a consequence Atom(uuid=5) is also stored badly.

There are several solution to consider:
* (greedy) - all atoms that are compatible with the atoms that already exists in the database are stored, but all atoms that would voilate the constraints are ignored and not inserted into the database (this concerns also their "parent" atoms recursively)
* (transaction) - if any atom fails to store, rollback the whole operation
* (uuid resolution) - change uids of atoms in the atomspace to match their equivalent atoms in the database, then store the whole atomspace into database without conflicts. But this would break assumption that atom uuid, so it seems to be very wrong way.

The greedy solution seems to be simplest to implement and it should be sufficient for this kind of rare corner use cases.

**Comment by linas** [comment] 2016-06-01 11:07
Yes, that's right.

* Calling `clear` like this is a user error -- the errors result because the atomspace is being used incorrectly.

* There probably should not even be a `clear` in the API -- there is no valid reason that I know of, for clearing an atomspace, except possibly in a few unit tests.  I don't recall how it even got into the API -- some mistake.

* The UUID should probably be removed from the Atom, and created/used/managed by the postgress backend only (or, more generally, by backends, in general, when communicating across multiple systems.)  The only reason to keep the UUID in the atom might be for performance reasons.

* However, removing the UUID from the atom is currently not possible,  because the python bindings are using it.  This is a python binding design flaw. There is supposed to be an open bug report for this, but I can't find it anywhere.

So, in the long run, I beleive that UUID's should be created and used only when atoms need to be communicated between multiple servers (or between the in-ram atomspace, and a database server, etc.)  Not the easiest solution, but I think its the best one.

Note also: the `pgsql-store` function is meant to be a batch-dump of the atomspace, and so, again, using it as above is a kind-of user-error -- one should never use it more than once.  The recommended usage is to use `store-atom` to store only those atoms that you really want to store, and to use `fetch atom` to fetch them.

So, in the short-run, this bug report is really a kind-of user error: the system was never designed to work this way -- it was designed with the very clear intent that the above would lead to errors.  So I'm not sure that anything really needs fixing here, other than to remove the UUID from the python bindings.

**Comment by leungmanhin** [comment] 2016-06-01 14:29
I agree that calling `clear` like this is a user error, and what I really want to do is indeed `store-atom`, however sometimes running things like `nlp-parse`, atoms will be generated and inserted into the atomspace directly, is there any way to located all those newly generated atoms? or maybe is there a way to always store atoms into the database as well when they are created?

On the other hand, if we keep creating new atoms and calling `pgsql-store` to store the whole atomspace from time to time, `pgsql-store` just slows down quite dramatically over time and this may not be very practical either...

**Comment by linas** [comment] 2016-11-12 14:46
OK, issue #923 -- moving UUID's out of atoms, got fixed in pull req #994 

In principle, this should allow this bug to be resolved. However, I just tested, and a different variant of this bug remains. It should now be fixable, though because the blockers mentioned in the previous comment are now fixed.

**Comment by linas** [comment] 2017-01-23 07:03
Please retest.  The postgres code has changed dramatically.

**Comment by linas** [comment] 2018-02-08 00:38
Closing. Stale bug report; the entire subsystem has been rewritten

**Closed by linas** 2018-02-08 00:38 UTC
Labels: bug, persistence
