### ISSUE TITLE
undefined symbol: PyExc_ImportError when using python-eval in scheme

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#2270] opened 2019-07-14 06:00 UTC
## Setup details
- Ubuntu 18.04 docker container = opencog/opencog-deps
- python grpcio version = 1.22.0
- cogutil git sha =33f871226 Merge pull request #183 from ngeiswei/cache-ghc-circleci
- atomspace git sha = d24f72381 Bug-fix; used incorrect list!

## Error detail
```scheme
$ LD_DEBUG_OUTPUT=ld.log LD_DEBUG=all guile
GNU Guile 2.2.3
scheme@(guile-user)> (use-modules (opencog) (opencog python))
scheme@(guile-user)> (python-eval "import grpc")
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("python-eval" "Python error: /usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError.\nTraceback (most recent call last):\nFile \"<string>\", line 1, in 
<module>\nFile \"/usr/local/lib/python3.6/dist-packages/grpc/__init__.py\", line 23, in <module>\n (/host/atomspace/opencog/cython/PythonEval.cc:694)\nFunction args:\n(import grpc)")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> 
```
LD_DEBUG_OUTPUT = [ld.log](https://github.com/opencog/atomspace/files/3389503/ld.log)

##  What I tried for a fix
Adding `-Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions` , as suggested by `python3-config --ldflags` to https://github.com/opencog/atomspace/blob/d24f72381c62e69ccec09db6db7371cc5e736064/opencog/cython/CMakeLists.txt#L13 as well as replacing RTLD_LAZY with RTLD_NOW made no difference https://github.com/opencog/atomspace/blob/d24f72381c62e69ccec09db6db7371cc5e736064/opencog/cython/PythonEval.cc#L296
The RTLD_LAZY flag was added for a fix to a similar issue https://github.com/opencog/atomspace/issues/669

**Comment by linas** [comment] 2019-07-14 06:44
The error is not being thrown by atomspace or opencog, its being thrown by grpc -- this:
```
/usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError.
```
which means that the library `cygrpc.cpython-36m-x86_64-linux-gnu.so` is the one with the missing symbol -- htis library is not a part of opencog. 

Now, here is what is suspicious: its in `/usr/local/` which means it was not installed by `apt-get` nor by any of the python installers. Which means it was hand-built ... my guess is that it was hand-built long ago, and links to something that no longer exists. .. you need to rebuild it, or get an offical copy via apt-get.

You can also list all missing symbols thike so
```
ldd -r /usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so
```

**Comment by linas** [comment] 2019-07-14 06:50
Oh, sorry, I just looked at #669 and you are right, maybe this is some weird dynamic loader thing.  

So, next guess is this: the library path that the dynamic loader is using is not the same library path that python expects. Maybe the missing symbol is supplied by some library that is not in the LIBPATH?  Does this work on some old version of atomspace? Can you `git bisect`? Last person to mess with python was @ferrouswheel and he might have more of a clue than I would ...

**Comment by linas** [comment] 2019-07-14 07:32
Try also messing with `LTDL_LIBRARY_PATH` and maybe `LD_LIBRARY_PATH`

**Comment by AmeBel** [comment] 2019-07-15 09:00
```
export LTDL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
```
Made no difference. 

Compiling atomspace against python 2.7.15 doesn't cause the issue.


__Shared object dependency when compiled against python 2.7.15__
```shell
$ ldd -r /usr/local/lib/opencog/libPythonEval.so 
	linux-vdso.so.1 (0x00007ffdc870e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8b8f979000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f8b8f3fc000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007f8b8f1e2000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007f8b8efdd000)
	libatom_types.so => /usr/local/lib/opencog/libatom_types.so (0x00007f8b8edcb000)
	libcogutil.so => /usr/local/lib/opencog/libcogutil.so (0x00007f8b8eb6c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8b8e7e3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8b8e5cb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8b8e1da000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8b8fdb4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8b8dfbd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8b8ddb9000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8b8dbb6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8b8d818000)
	libbfd-2.30-system.so => /usr/lib/x86_64-linux-gnu/libbfd-2.30-system.so (0x00007f8b8d4c8000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f8b8d299000)
```

__Shared object dependency when compiled against python 3.6.8__
```shell
$ ldd -r /usr/local/lib/opencog/libPythonEval.so 
	linux-vdso.so.1 (0x00007ffd91fb3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffbf5057000)
	libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007ffbf49a5000)
	libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007ffbf478b000)
	libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007ffbf4586000)
	libatom_types.so => /usr/local/lib/opencog/libatom_types.so (0x00007ffbf4374000)
	libcogutil.so => /usr/local/lib/opencog/libcogutil.so (0x00007ffbf4115000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffbf3d8c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffbf3b74000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffbf3783000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffbf5492000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ffbf3551000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffbf3334000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffbf3130000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ffbf2f2d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffbf2b8f000)
	libbfd-2.30-system.so => /usr/lib/x86_64-linux-gnu/libbfd-2.30-system.so (0x00007ffbf283f000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007ffbf2610000)
```

There are undefined symobls in both the python2 and python3 version of `cygrpc.so`.
`ldd -r /usr/local/lib/python2.7/dist-packages/grpc/_cython/cygrpc.so` gives [cygrpc.so_undefined_symbols_py2.7.15.txt](https://github.com/opencog/atomspace/files/3391506/cygrpc.so_undefined_symbols_py2.7.15.txt)
`ldd -r /usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so` gives [cygrpc.so_undefined_symbols_py3.6.8.txt](https://github.com/opencog/atomspace/files/3391507/cygrpc.so_undefined_symbols_py3.6.8.txt)

**Comment by ferrouswheel** [comment] 2019-07-15 09:04
Where is grpc coming from? How is it compiled?

Does the error happen with other compiled python modules?

**Comment by AmeBel** [comment] 2019-07-15 09:13
grpc was install using pip. 

Yes numpy causes the error too
```scheme
scheme@(guile-user)> (use-modules (opencog) (opencog python))
scheme@(guile-user)> (python-eval "import numpy")    
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("python-eval" "Python error: \nImporting the multiarray numpy extension module failed.  Most\nlikely you are trying to import a failed build of numpy.\nIf you're working with a numpy git repo, try `git clean -xdf` (removes al
l\nfiles not under version control).  Otherwise reinstall numpy.\n\nOriginal error was: /usr/lib/python3/dist-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_SystemError\n.\nTraceback (most recent call last):\nFile \"<string>\
", line 1, in <module>\nFile \"/usr/lib/python3/dist-packages/numpy/__init__.py\", line 142, in <module>\nFile \"/usr/lib/python3/dist-packages/numpy/add_newdocs.py\", line 13, in <module>\nFile \"/usr/lib/python3/dist-packages/numpy/lib/__init__.py\", line 8, in <m
odule>\nFile \"/usr/lib/python3/dist-packages/numpy/lib/type_check.py\", line 11, in <module>\nFile \"/usr/lib/python3/dist-packages/numpy/core/__init__.py\", line 26, in <module>\n (/host/atomspace/opencog/cython/PythonEval.cc:694)\nFunction args:\n(import numpy)")
'.

```
yes numpy causes the error to

**Comment by AmeBel** [comment] 2019-07-15 09:32
If numpy is installed using apt then you get the above symbol as missing.

If it is installed using pip then you get the following
```scheme
scheme@(guile-user)> (use-modules (opencog) (opencog python))
scheme@(guile-user)> (python-eval "import numpy")
ERROR: In procedure opencog-extension:
Throw to key `C++-EXCEPTION' with args `("python-eval" "Python error: \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the multiarray numpy extension module failed.  Most\nlikely you are trying to import a failed build of numpy.\nH
ere is how to proceed:\n- If you're working with a numpy git repository, try `git clean -xdf`\n  (removes all files not under version control) and rebuild numpy.\n- If you are simply trying to use the numpy version that you have installed:\n  your installation is br
oken - please reinstall numpy.\n- If you have already reinstalled and that did not fix the problem, then:\n  1. Check that you are using the Python you expect (you're using /usr/bin/python3),\n     and that you have no directories in your PATH or PYTHONPATH that can
\n     interfere with the Python and numpy versions you're trying to use.\n  2. If (1) looks fine, you can open a new issue at\n     https://github.com/numpy/numpy/issues.  Please include details on:\n     - how you installed Python\n     - how you installed numpy\n
     - your operating system\n     - whether or not you have multiple versions of Python installed\n     - if you built from source, your compiler versions and ideally a build log\n\n     Note: this error has many possible causes, so please don't comment on\n     an
 existing issue about this - open a new one instead.\n\nOriginal error was: /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError\n.\nTraceback (most recent call last):\nFile \"<strin
g>\", line 1, in <module>\nFile \"/usr/local/lib/python3.6/dist-packages/numpy/__init__.py\", line 142, in <module>\nFile \"/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py\", line 71, in <module>\n (/host/atomspace/opencog/cython/PythonEval.cc:694)\nFu
nction args:\n(import numpy)")'.
```

**Comment by linas** [comment] 2019-07-15 17:58
and you ran `ldconfig` at last once, as root?

**Comment by linas** [comment] 2019-07-15 18:48
A quick overview of shared library loading might help solve the problem.

* When an executable is started, it is fetched from disk and loaded into RAM.
* When loaded into RAM, the PLT section (Procedure Linkage Table) is  initialized so that all function calls are linked to a special library called `ld.so`
* The `ld.so` library is provided by glibc, and is part of the linker-loader subsystem. (Sometimes `ld.so` is called THE linker-loader. Its both a library and a command.)
* Each function call symbol in an external library has it's own entry in the PLT
* (There are other symbols too; lets ignore those)
* When your executable makes a call to a symbol, that symbol is looked up in the PLT, 
* The glue code in the PLT causes execution to jump to the code in `ld.so`.
* Here, `ld.so`  tries to figure out which function call it should have been, in which library.
* The `ld.so` performs a complicated search to find the correct library, involving an `RPATH` settings in the executable, as well as half-a-dozen environment variables, including `LD_LIBRARY_PATH` and others.
* It also uses the cached list of libraries maintained by `ldconfig` and stored in `/etc/ld.so.cache`
* (The cache was previously built by `ldconfig`, and that command looks at `/etc/ld.so.conf` and/or `/etc/ld.so.conf.d/*`)
* After `ld.so` finds the right function in the right library, it loads that library into RAM. 
* It alters the  PLT table, installing glue code into the correct final destination (so that if/when the executable ever calls that PLT entry a second time, it will jump directly to the right place.)

This process repeats, ad infinitum for each new function call. If a shared library calls a shared library, same deal. And on and on.  (This is called "lazy loading")

If your executable dynamically opens a library, by calling `dlopen` something somewhat similar happens, except that now, `dlopen` does the first few stages of setup (loading the library into RAM, initializing the PLT table, etc.) Also, `dlopen` can do either lazy or eager linking.  Eager linking is nice because it lets you know immediately if the dlopen'ed library is missing something.  (The `dlopen` fails on the spot) Lazy linking is nice, cause its faster, but if the loaded library is borken, you won't know until much later (and maybe never).

When you run `ldd -r` on an executable or on a library, it does most of the above: scanning all the symbol tables, and figuring out the PLT entries in an "eager" fashion. It tries to resolve all of the symbols.  It then prints a list of the libraries that it needed to load, and it prints a list of symbols it could not resolve.

When `ldd -r cyrpc.so` fails, its the missing symbols are typical of python.  So either it is not finding the python libraries, or the libraries don't contain those symbols. Why? I dunno.  A broken build might mean that those symbols do not exist. Maybe your python library has those symbols stripped out, and you need to install a python which actually exports them. Maybe there might be a broken `RPATH` in cyrpc.so? Maybe `ldd` decided not to use the python libraries for some reason (because it was told not to, or because of version skew?)  (symbols can have attached version numbers...)

You can look at the symbols exported by a library with `nm` - it will also print the version of the symbol. ...

**Comment by linas** [comment] 2019-07-15 19:01
Your ldd dump is this:
```
        linux-vdso.so.1 (0x00007ffec2beb000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa8ab352000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa8ab133000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa8aadaa000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa8aaa0c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa8aa61b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa8abb52000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa8aa403000)
undefined symbol: PyExc_ImportError     (/usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so)
undefined symbol: PyExc_StopIteration   (/usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so)
undefined symbol: PyGen_Type    (/usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so)
undefined symbol: PyFrozenSet_Type      (/usr/local/lib/python3.6/dist-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so)
... etc.
```

Painfully obvious is that nowhere in that list is a python library.  I would have expected something like
```
libpython3.5m.so => /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
``` 
but its not there.  Nor is
```
libpython3.5m.so => (Undefined)
```
which also sometimes happens.  So how the heck is `cyrpc.so` supposed to find `libpython` ??? Maybe it too is using `dlopen()` and that `dlopen` is failing ??  Also -- review man page for `dlopen`

Maybe `pip install` has some other python libraries installed somewhere else, where `ldd` can't find them. Again .. `ldd uses what `/etc/ld.so.cache` provides ... rebuild the cache with `ldconfig` after adding th correct library path to `/etc/ld.so.conf` and/or `/etc/ld.so.conf.d/*`

That's all I got. Review the `dlopen` man page, and the `nm` man page ...

**Comment by ferrouswheel** [comment] 2019-07-16 00:00
I reproduced this locally.

I could fix this, without rebuilding, by starting guile with:

`LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0" guile -L opencog/scm/`

Problem is that the `dlopen` call is using `libpython3.5.so` instead of `libpython3.5m.so`. The former is not the python library linked against while building and the latter uses PyMalloc. I'm guessing that, for Python 2.7, the PyMalloc dynamic library is not used by default and this is why it works.

We should probably use the last part of the CMake variable `PYTHON_LIBRARY` instead of constructing the python library name [with `PY_MAJOR_VERSION` and `PY_MINOR_VERSION`](https://github.com/opencog/atomspace/blob/d24f72381c62e69ccec09db6db7371cc5e736064/opencog/cython/PythonEval.cc#L295).

**Comment by ferrouswheel** [comment] 2019-07-16 01:05
Fixed in #2273

**Comment by AmeBel** [comment] 2019-07-16 02:43
@ferrouswheel #2273 fixes it, but I don't understand why. Both libpython3.6m.so and libpython3.6.so exist in ubuntu 18.04 and they are symlinks to libpython3.6m.so.1, so why does it matter?

**Comment by AmeBel** [comment] 2019-07-16 02:52
If a symbol is searched for in the PLT, then why will the name of the file matter? Especially if they are symlinks to the same file, and thus result in the same set of symbols.

**Closed** 2019-07-16 03:16 UTC
Labels: bug, python

**Comment by linas** [comment] 2019-07-16 03:18
> why will the name of the file matter?

It shouldn't. unless there are two files or symlinks in the system. in different locations, both with the same name, but having different contents, in which case craziness happens.

The other possibility is that you have python 3.5 installed, but have libraries for 3.6, and before the patch, it was dlopening libpython3.5 ... or something like that ...

**Comment by ferrouswheel** [comment] 2019-07-16 03:24
Ah, I assumed I had both. I don't. I only have `/usr/lib/x86_64-linux-gnu/libpython3.6m.so`.

So at least for me, the `dlopen` call was failing, but we don't check the return code so I never noticed.

Python2.7 only has `/usr/lib/x86_64-linux-gnu/libpython2.7.so`, no `m` variant. Sorry for assuming both variants exist (on some platforms/distributions, Python will be shipped with both)

**Comment by AmeBel** [comment] 2019-07-16 04:23
Well, I will put this in the 'weird leaky abstractions' bucket. 

@linas @ferrouswheel Thanks :-)

**Comment by linas** [comment] 2019-07-16 04:41
I'm not entirely clear on this, but I think the whole point of the *nix package manager, and the NixOS and Guix distributions is to nip this problem in the bud. The historical reason that Linux evaded the 1990's MSWin DLL-hell was it was just a little bit smarter in package installs. ... but only a little smarter ... so the old boss was defeated ...  level-up ... with the advent of things like `pip` and `maven` and `cpan`, you get to face a new boss, same as the old boss, but trickier, this time.  Mix `pip` and `apt` on the same machine, and you're asking for trouble.... 

It's just not clear to me if nix can actually solve this problem. And of course, if you backslide, and mix nix with pip, well :-)
