### ISSUE TITLE
another C error crashing python

### ISSUE THREAD

**Issue by alexander-gabriel** [opencog/atomspace#2524] opened 2020-03-03 19:15 UTC
Here's another case where a C exception isn't handled properly by python.
I don't have code that reproduces this currently as it was thrown in the middle of an experiment run and it's not trivial to debug which part of the code caused it.

```
terminate called after throwing an instance of 'opencog::AssertionException'
  what():  Atom table is not null! (/home/rasberry/git/atomspace/opencog/atoms/base/Atom.cc:274)
```

**Comment by linas** [comment] 2020-03-03 23:02
The general solution for having python catch eceptions is to go through the `*.pxd` files that define the C interfaces, and append `except +` to every function that might throw an exception.

Now, most exceptions are due to "user error", user created some badly-formatted expression.  Not here. This error is saying that somehow, something got ahold of an atom that already is/was in an atomspace, and is trying to re-insert it again.It's a kind-of must-never-happen situation,  and arguable should be an assert + coredump. 

At the moment, the only thing I can think of involves a second atomspace - python creates an atom in one atomspace, memorizes the pointer to it, and then uses it in a second atomspace ... which .. well, actually that could/should work-ish, but is flirting with dangerous territory.  Unusual multi-atomspace scenarios were never really clarified, because its not entirely clear what "the right answer" is in these corner cases.  Is your code using multiple atomspaces? (you might be doing so unwittingly...!?)

**Comment by linas** [comment] 2020-03-03 23:15
Oh, line 274  is an assert. A stack trace would be useful ... a core file would be better.

**Comment by linas** [comment] 2020-03-03 23:16
There should be a stack trace printed in `opencog.log` in... some directory (these log files get littered all over the file system; sorry..)

**Comment by linas** [comment] 2020-03-27 20:51
Closing. Without a trace or log-file, there's nothing to be done, here.

**Closed by linas** 2020-03-27 20:51 UTC
Labels: bug, python

**Comment by einalex** [comment] 2020-05-21 22:11
I now have a situation where I can reproduce this
```  File "opencog/bindlink.pyx", line 13, in opencog.bindlink.execute_atom (/home/rasberry/git/atomspace/build/opencog/cython/opencog/bindlink.cpp:1093)
RuntimeError: Atom table is not null! (/home/rasberry/git/atomspace/opencog/atoms/base/Atom.cc:274)```

**Comment by linas** [comment] 2020-05-21 22:51
Hi @einalex yes, I very unexpectedly found that one earlier today, 
its fixed in #2626 which will be merged shortly.  Here's the root cause:
no one has searched for the presence of StateLinks before. Now,
Statelinks are defined so that there can only ever be "one of them".
ever (so that something is always just in one unique state)  The pattern
engine uses a temporary atomspace in which it evaluates partial results
(so as not to pollute the main atomspace with half-finished and ultimately
rejected changes) ...

Sooo ...  the presence/absence of the StateLink resulted in the creation
of a "temporary" StateLink, which clobbered the one in the main AtomSpace
and that clobber resulted in the crash you report.

The fix is to allow child/derived atomspaces to over-ride and hide any
StateLinks in the main atomspace. This is also how Value and TruthValue
changes are handled, when the main atomspace has been marked read-only;
a copy-on-write operation is performed. The temporary, and everything it
contains, disappears when the search is completed.

**Comment by linas** [comment] 2020-05-21 23:00
@einalex -- the battery of tests, spurred by you bug report, is here:
https://github.com/opencog/atomspace/pull/2626/files#diff-7aae5369c58a4de5af1e9a721b047ca7

Look them over, it might help. I think other reasonable variants will work.
Note also: if you are interested in OrLink, you may want to look at ChoiceLink 
instead.  Choice is a "menu choice" -- "pick one" which is similar to but not really
the same as a boolean-or set-union operation.  Many people naively assume
they're the same thing, and the subtle differences cause trouble, so we're
careful to distinguish the two.

See wiki for docs https://wiki.opencog.org/w/ChoiceLink

**Comment by einalex** [comment] 2020-05-21 23:06
@linas I do need that truth evaluation though.. and I can't rely on there only being presentlinks involved...in fact my system generates queries dynamically and at the moment doesn't pay too close attention to what it assembles. Changing that to use lots of if/else special case handling would be quite unelegant.

**Comment by linas** [comment] 2020-05-21 23:20
I have no clue what you are referring to, in the above comment, or what,
exactly, is inelegant.  I'm not a mind-reader. 

Again -- the pattern engine is not the same as the URE; it does not do
any logic or inference or deduction. It is a query engine: it reports on
the contents of the atomspace, and "nothing more".  It never looks at 
truth values, nor does it modify them (... unless you apply some custom
predicate.  That is, in addition to searching the atomspace, you can
ask it to filter out certain unwanted results with predicates that evaluate
to true/false.   This additional filtering ability makes the engine quite
flexible and powerful, but it's core function is to provide yes/no answers
about the contents of the atomspace.)

**Comment by linas** [comment] 2020-05-21 23:34
@einalex I mean -- if you are hitting bugs or what feels like bugs,
then open new github issues.

If there are usability problems ... send either emails or if it is a
very focused usability problem, almost a bug, then a github issues.
The general goal is to make the system usable and easy to use
and fast all in one... feedback from people like you drives this.

**Comment by einalex** [comment] 2020-05-21 23:42
@linas ah, my apologies. I was referring to this: https://wiki.opencog.org/w/ChoiceLink (the pattern matching section)

**Comment by linas** [comment] 2020-05-22 02:35
@einalex What about that section?

**Comment by einalex** [comment] 2020-05-22 17:37
that section cautions the user about truth values of atoms not getting taken into account.

**Comment by linas** [comment] 2020-05-23 01:07
> that section cautions the user about truth values of atoms not getting taken into account.

Well, nothing in the pattern engine examines truth values, so that remark is a bit out of place.

If you want to accept/reject a match, based on the attached TV, you can do this:
```
(BindLink   ; or GetLink or QueryLink or  JoinLink or MeetLink ...
      (Variable "X")
     ... other stuff/constraints...
    (GreaterThan (StrengthOf (Variable "x")) (Number 0.42))
    ... etc....
)
```
In the above, during the search, whatever matches `Variable "x"`, the "strength" of the truth value on it is examined, and if its greater than 0.42, then the match is accepted, otherwise its rejected.

Besides `StrengthOf` there is also `ConfidenceOf` and `CountOf` (handy, if accumulating counts on a `CountTV`) and generically, there is a `ValueOf` for generic values of any kind.  Together with `PlusLink`, `TimesLink` you can implement assorted formulas, (there's even a step function and an absolute-value, for convenience, but no trigonometry or complex numbers or special functions) Also, with either `RandomNumberNode` or with RandomValue` you can do stochastic sampling, if you wish.

**Comment by linas** [comment] 2020-05-23 01:11
updated last comment
