### ISSUE TITLE
Possible bug in virtual-term detection code?

### ISSUE THREAD

**Issue by AmeBel** [opencog/atomspace#533] opened 2015-12-14 09:29 UTC
Why is the choice of when to evaluate an evaluatable term, dependent on the number of unquoted variables?
[Here](https://github.com/opencog/atomspace/blob/master/opencog/atoms/pattern/PatternLink.cc#L614-L621), for the case of evaluatable terms,  it is commented that 

```c++
			// But they're virtual only if they have two or more
			// unquoted, bound variables in them. Otherwise, they
			// can be evaluated on the spot.
```

##### Question

Since it is a black-box term why does the number of unquotted variables in the term be `>=2`to decide when to evaluate?

For example, the following term isn't 'virtual'
``` scheme
(EvaluationLink
                (GroundedPredicateNode "scm: cog-tv")
                (ListLink
                    (VariableNode "z"))
```
while the following is
```scheme
(EvaluationLink
                (GroundedPredicateNode "scm: cog-equal?")
                (ListLink
                    (VariableNode "y")
                    (VariableNode "z"))
```
but one can't tell whether `cog-equal?` will run slower than `cog-tv` by merely the number of arguments.

**Comment by AmeBel** [comment] 2015-12-14 09:46
The same can be said for executable terms, specially for the case of `ExecutionOutputLink`

**Comment by linas** [comment] 2015-12-15 04:08
If you have a value for x, then you can evaluate f(x) on the spot, then and there.

To evaluate f(x,y), you need to know both x and y.  If you do know both, then I guess its OK to evaluate on the spot (and I guess the code should be fixed to do this); however, I guess the code makes the assumption there is that one will be known, but not the other.

The reason for this assumption is that such graphs "typically" consist of multiple disjoint parts, with x grounded in one part, and y grounded in another, and only f(x,y) connects the two parts, thus you never know both x and y until you found complete sets for both.   An example:

find cities $m with population $x and countries $c with population $y such that $y < $x (the city is larger than the country)

For each city you find $x, you don't want to repeat the search for countries $y over and over.. the search is expensive. .. so instead, find all the cities, then find all the countries, and then a pair of nested for-loops, over $x and $y, perform the evaluation f(x,y)

**Comment by linas** [comment] 2015-12-15 04:23
It is possible that the code is buggy; for example, if the query is this:  

find cities $m with population $x and phone numbers $y such that $x < $y

In this case, the search over cities will give both $x and $y at the same time, and the evaluation can be done on the spot.  This query just has one single connected graph, unlike the city/coutnry example above, which has two disconnected pieces.

I no longer recall if this case is detected and handled correctly. Given the `if (2 <= 
num_unquoted_in_tree()` maybe its done wrong. Not sure.  Could you check?  Is there a way to have a unit test for this?  I guess you could count how many times f(x,y) got called in test case -- it should get called N times, not N^2 times.

**Comment by linas** [comment] 2015-12-16 19:36
The two simplest test cases work fine. I just checked. More complex test cases, I'm not sure about.  Here are the simple ones:
```
(Evaluation (Predicate "phone") (ListLink (Concept "Paris") (Number 10)))
(Evaluation (Predicate "pop") (ListLink (Concept "Paris") (Number 5)))
(Evaluation (Predicate "org") (ListLink (Concept "Paris") (Concept "city")))

(Evaluation (Predicate "phone") (ListLink (Concept "Berlin") (Number 10)))
(Evaluation (Predicate "pop") (ListLink (Concept "Berlin") (Number 15)))
(Evaluation (Predicate "org") (ListLink (Concept "Berlin") (Concept "city")))

(Evaluation (Predicate "phone") (ListLink (Concept "Hong Kong") (Number 10)))
(Evaluation (Predicate "pop") (ListLink (Concept "Hong Kong") (Number 20)))
(Evaluation (Predicate "org") (ListLink (Concept "Hong Kong") (Concept "city")))

(Evaluation (Predicate "pop") (ListLink (Concept "Barbados") (Number 7)))
(Evaluation (Predicate "org") (ListLink (Concept "Barbados") (Concept "country")))

(Evaluation (Predicate "pop") (ListLink (Concept "Japan") (Number 30)))
(Evaluation (Predicate "org") (ListLink (Concept "Japan") (Concept "country")))

(define cnt 0)
(define (cmp nx ny)
   (define x (string->number (cog-name nx)))
   (define y (string->number (cog-name ny)))
   (set! cnt (+ cnt 1)) 
   (if (> x y) (stv 1 1) (stv 0 1)))
   
(define phone-inversion
(Get (And
   (Evaluation (Predicate "phone")
       (ListLink (Variable "$city") (Variable "#phone")))
   (Evaluation (Predicate "pop")
       (ListLink (Variable "$city") (Variable "#pop")))
   ;(GreaterThan 
   ;  (Variable "#phone") (Variable "#pop"))
   (EvaluationLink
      (GroundedPredicateNode "scm: cmp")
      (ListLink (Variable "#phone") (Variable "#pop")))
   ))
)  

(use-modules (opencog exec))

(cog-execute! phone-inversion)

cnt
; value printed should be 3 not 9=3x3 because there are three cities, and three
; compares total, as opposed to 9 city-pairs.

(define pop-inversion
(Get (And
   (Evaluation (Predicate "org")
       (ListLink (Variable "$city") (Concept "city")))
   (Evaluation (Predicate "pop")
       (ListLink (Variable "$city") (Variable "#city-pop")))
   (Evaluation (Predicate "org")
       (ListLink (Variable "$state") (Concept "country")))
   (Evaluation (Predicate "pop")
       (ListLink (Variable "$state") (Variable "#state-pop")))
   (EvaluationLink
      (GroundedPredicateNode "scm: cmp")
      (ListLink (Variable "#city-pop") (Variable "#state-pop")))
   ))
)  

(set! cnt 0)
(cog-execute! pop-inversion)
cnt
; 6 = 2 x 3 should be printed, since 2 countries get compared against 3 cities.
```

It is possible that some sort of multi-way compare of the two cases above doesn't work right; I did not study the code...

**Comment by linas** [comment] 2015-12-16 20:01
Ohh -- here's one: EqualLink can be, should be traced through -- in fact, equality for two variables really means that the two variables should be condensed into one.

**Comment by linas** [comment] 2015-12-16 20:33
Slightly unexpectely, using EqualLink only results in 3 evaluations. That is because EqualLink is a clear-box link, and gets evaluated first, thus ruling out the need for excessive inequality compares.
```
(define (careful-cmp nx ny)
   (if (not (eq? (cog-type nx) 'NumberNode)) (stv 0 1))
   (if (not (eq? (cog-type ny) 'NumberNode)) (stv 0 1))

   (let ((x (string->number (cog-name nx)))
         (y (string->number (cog-name ny))))
      (set! cnt (+ cnt 1))
      (if (> x y) (stv 1 1) (stv 0 1))))

(define phone-cross
(Get (And
   (Evaluation (Predicate "phone")
       (ListLink (Variable "$city-a") (Variable "#phone")))
   (Evaluation (Predicate "pop")
       (ListLink (Variable "$city-b") (Variable "#pop")))
   (Equal (Variable "$city-a") (Variable "$city-b"))
   (EvaluationLink
      (GroundedPredicateNode "scm: careful-cmp")
      (ListLink (Variable "#phone") (Variable "#pop")))
   ))
)

(cog-execute! phone-cross)
```

**Comment by linas** [comment] 2015-12-16 20:53
Not using clearbox equaltiy does show the combinatoric explosion:
```
(define (eq-atom x y)
(if (equal? x y) (stv 1 1) (stv 0 1)))

(define phone-black
(Get (And
   (Evaluation (Predicate "phone")
       (ListLink (Variable "$city-a") (Variable "#phone")))
   (Evaluation (Predicate "pop")
       (ListLink (Variable "$city-b") (Variable "#pop")))
   (Evaluation
      (GroundedPredicate "scm: eq-atom")
      (ListLink (Variable "$city-a") (Variable "$city-b")))
   (Evaluation
      (GroundedPredicate "scm: careful-cmp")
      (ListLink (Variable "#phone") (Variable "#pop")))
   ))
)

(cog-execute! phone-black)
```

**Comment by AmeBel** [comment] 2015-12-17 06:39
ok, I get the intention behind the having `2 <= num_unquoted_in_tree` for categorizing whether a term is virtual, fixed or black, if I am not mistaken it is used for signaling the Pattern matcher engine, on how to go about grounding this terms more efficiently. 

On opening this issue, my intention was for using the categorization for the purpose of rule-selection in the context of action-selection wherein,
*  the terms descirbe the context/state that should be satisfied for the rule to be run.
*  the atomspace and the external world it interacts with through evaluatable/executable terms constitue the environment.

On selecting a rule, one has to evaluate whether the context/state are satisfied within the environment without having to modify the environment(specially the external world). Short of simulating the external world in the atomspace, the way to do that is to derive a new rule, that is cleaned out of evaluatable/executable terms. Now, after your explanation, the option that I could see for doing that and still maintain the signaling to the pattern-matcher engine are,
1. copy-paste-edit the `unbundle_virtual` method in my class to fit my case, basically removing `2 <= num_unquoted_in_tree` and maintain the semantics changes as the role of atom-types changes,
2. add a new variable PatternLink to hold the information I need, like `state_modifying`
I prefer two, but there might be another way to achieve the same, what is your suggestion?

**Comment by linas** [comment] 2015-12-17 07:01
I don't quite understand what you are trying to do.  My quick reaction is that you should invent a new link type, have it inherit from PatternLink, write a C++ class to perform the additional analysis that you need to do.

Yes, the PatternLink is very strongly tied to the pattern matcher: it unbundles and "pre-compiles"  static parts of the pattern so that the pattern matcher can do less work.  It is subject to change, whenever someone finds some better way of doing things.   It makes me very nervous that some other component, not really part of the pattern matcher, is depending on the pattern-matcher internals working in some specific way.  The internals *will* change; the only guarantee is that the callbacks won't change and the general API won't change.

It sounds like you need to do some kind of pre-analysis as well, and having that sit in C++ code in a derived class seems like a perfectly fine way to do things.

So -- GetLink SatisfactionLink and BindLink all inherit from PatternLink.   Create a RuleLink or something like that, and derive straight from PatternLink, or derive from one of those.  Either way, cog-execute! will be able to run the new RuleLink, automatically, if you set it up right.

**Comment by linas** [comment] 2015-12-17 07:08
Re this problem: "On selecting a rule, one has to evaluate whether the context/state are satisfied within the environment without having to modify the environment(specially the external world). "   -- If you use GetLink instead of BindLink, you won't have this problem.

GetLink simply performs a search of the atomspace, and gives you the results.  BindLink does what GetLink does, but also does a re-write, a PutLink as the last step.    Running GetLink is guaranteed not to modify the main atomspace; it uses it's own scratch space, if it needs to.  

The wikipage shows exactly how any given BindLink can be converted to a Get/Put pair, and vice-versa; they are completely interchangeable, and I'm finding Get/Put is easier to work with for what I'm currently working on.

**Comment by linas** [comment] 2015-12-17 07:16
So, using GetLink instead of BindLink might be your easiest solution, maybe; not sure. But I want to mention another, crazier, maybe easier, but maybe harder solution: use the "pattern recognizer"   -- it was designed to solve a problem a lot like what you are describing: given a state of the world, find me all the rules that I can run. 

See /examples/aiml/recog.scm -- maybe we can do something like that, but better, to solve the action-selection problem that you have?

**Comment by linas** [comment] 2015-12-17 07:20
Its late at night here, and my mind is melting, so maybe this is crazy .. but ... if your goal with action selection is to find what rules can be applied at any given time, then yes, the recognizer is really the thing that you want.

**Comment by AmeBel** [comment] 2015-12-17 07:41
i haven't the studied the recognizer, will do that, but for clarification on your previous comments,

GetLink/SatisfactionLink will work once the BindLink is cleaned of all the evaluatable/executable terms (aka virtual-links as per the draft specification of atomese http://wiki.opencog.org/wikihome/index.php/Virtual_links :smile: ). That is what i am doing [here](https://github.com/AmeBel/opencog/blob/openpsi/opencog/planning/Action.cc#L80) , when i discovered  `2 <= num_unquoted_in_tree`

**Comment by AmeBel** [comment] 2015-12-17 12:30
on pattern recognition using the implementation in Recognizer.cc would be two expensive, as it isn't known whether the pattern to be recognized is existant, in other words , action-selection is a patter matching problem as there are two many patterns to be recognized(at most the whole atomspace minus the rules) against  a handful of rules.

**Comment by linas** [comment] 2015-12-17 16:19
So, perhaps you need to search only a subset of the atomspace?

I'm not sure what you mean by "will work once cleaned of all the evaluatable/executable terms" -- clearly, the examples above will fail.  Another way to think of virtual links is to think of them as an alternative factorization for the search process.  this is just like the tactorization of a variety into prime ideals is not unique; crudely, you can factor in series, or in parallel, or in other cross-linked ways. In this case, there is a recursive call to ground each of the sub-pieces before grounding the whole.  Its kind-of like Hilbert's nullstellensatz, I guess.  Same general idea.

**Comment by linas** [comment] 2015-12-17 16:33
How about this: can you describe, more clearly, and more fully, what you are trying to do, either here, or maybe on a wiki page (that will evolve into a "how action selection works" wiki page?

If the recognizer is the right general idea, but performs too-broad a search, maybe that can be fixed. Viz by default, the "find starter" searches the whole atomspace; but this can be easily limited to a subset.

I've previously noted that the PutLink can be used as a kind-of filter: given a bigger set (but not the whole atomspace) it can search that set and return only a smaller subset.  This is an interesting idea, perhaps it can be extended.

**Comment by linas** [comment] 2016-08-13 02:28
closing, this conversation went in too many directions, without any resolution.  Anyway, I think all-new, all-improved lgos are now being used in openpsi.

**Closed by linas** 2016-08-13 02:28 UTC
Labels: pattern-matcher, question
