### ISSUE TITLE
inconsistent behavior of bindlink with empy variable list

### ISSUE THREAD

**Issue by noskill** [opencog/atomspace#2304] opened 2019-07-30 14:10 UTC
```python    
atomspace = AtomSpace()
initialize_opencog(atomspace)
imp1 = ImplicationLink(
        VariableNode("X0"),
        VariableNode("X1")
    )
imp2 = ImplicationLink(
        VariableNode("X1"),
        VariableNode("X5"))
varlist = VariableList()
bind = BindLink(varlist, imp2, imp2)
print(execute_atom(atomspace, bind))
```
returns 
```scheme
(SetLink
  (ImplicationLink
    (VariableNode "X1")
    (VariableNode "X5")
  )
)
```

while     
bind = BindLink(imp2, imp2)

returns empty set, I would expect empty variable list to be equivalent to not using variable list

**Comment by vsbogd** [comment] 2019-07-30 14:33
@noskill , what is the difference between first and second call? I see `bind = BindLink(imp2, imp2)` and `bind = BindLink(imp2, imp2)`

**Comment by noskill** [comment] 2019-07-30 14:43
Thanks Vitaly, it should be bind = BindLink(varlist, imp2, imp2)

**Comment by linas** [comment] 2019-07-30 15:17
In scheme:
```
(define i2 (Implication (Variable "x1") (Variable "x5")))
(cog-execute! (Bind i2 i2 ))
```
returns
``` 
(SetLink
)
```
Because there was no explicit variable declaration, a search for all variables in the body was made: x1 and x5 were found, and so that is equivalent to
```
(cog-execute!  (Bind (VariableList (Variable "x1") (Variable "x5")) i2 i2 ))
```
and the empty set is the correct result.

The other form is this:
```
(cog-execute!  (Bind (VariableList) i2 i2 ))
```
In this case, there are no variables at all. So `i2` is a constant.  The first `i2` is the pattern, its a constant, it always matches, its a hit. The second `i2` is the rewrite, its a constant, there's nothing to be rewritten, so it is repeated verbatim as the only possible output.

**Comment by linas** [comment] 2019-07-30 17:50
See also #2306 -- closing, not a bug.

**Closed by linas** 2019-07-30 17:50 UTC
Labels: pattern-matcher, question
