### ISSUE TITLE
TypeIndex Unsafe?

### ISSUE THREAD

**Issue by rTreutlein** [opencog/atomspace#945] opened 2016-10-18 08:05 UTC
While working on #944 I noticed the following in the type index. https://github.com/opencog/atomspace/blob/master/opencog/atomspace/TypeIndex.h#L43-L50

In short, the TypeIndex uses an iterator as an interface to stay performant but this Iterator is not threadsafe.
Now I am unsure in how many places the iterator actually gets used. The Atomspace provides an interface that provides a copy of that data which is threadsafe but also the iterator directly.

Either way, this does seem like it could be a big problem. Just wanted to hear others opinions on this.

If it is a problem then I am unsure about how to best fix it. You might be able to rewrite the iterator in a way that stops it from crashing but that might lead to it not returning all Atoms if there was a recent insert/deletion. Or you could not use the iterator design which would be threadsafe but a lot less performant.

**Comment by linas** [comment] 2016-10-18 22:54
Yep. Not sure what to say. So I'll say it all.

1) Long ago, I decided that the indexes were over-engineered, and implemented the wrong abstraction, and that there is this other, better API they should use. I don't recall what that is, though. 

2) You can measure performance with the benchmark. However, I suspect that the benchmark is broken, these days.  it needs love and attention.

3) For the atomspace, it turns out that you can get some very subtle bugs, if you make the locks be per-index, instead of the current design.  The problem is, roughly, if you have multiple threads trying to add or even access the same atom, and some, but not all of the indexes have been updated and have become publically visible, then one thread using one index, might think an atom exists, while another thread, using an index that has not yet been updated, thinks that the atom does not exist (and so tries to add it to the atomspace, etc). Eventually the wheels come off and it collapses in a big mess.  I had tried this with the "async atomspace update"; there's some remnants of this in the code, but it cannot work in the naive way I was thinking about it.  

I'm sure that there is a solution for this, now that we know the problem, but architecting and performance-tuning this is not something I can devote time to, this year.  However, for the mid-term, having a high-performance, fully parallelizable/scalable way of updating the indexes is very important.  So if you get the urge to work in this area, go for it.

One more point:
4) The concept of a centralized set of indexes that are ACID is sort-of ingrained into much of the atomspace implementation https://en.wikipedia.org/wiki/ACID and we all now know that a decentralized BASE https://en.wikipedia.org/wiki/Eventual_consistency can scale much better, usually.  So the trick is, can we make the atomspace add and delete be fast and scalable, while preserving enough consistency that we can at least add atoms to it in a fashion that is not self-corrupting?  This requires some thought, and, once one gets going, I'm sure a number of really neat ideas will fly to mind.  Trick is to capture them, and find the time to implement them.

**Comment by linas** [comment] 2016-11-02 18:05
FYI, during the recent conversion to hashes, I removed all of the indexes, except for the TypeIndex.

**Comment by linas** [comment] 2017-07-25 20:36
closing. Most of the indexes have been removed; general atomspace performance tuning will require a more holistic view of what's going on in there.

**Closed by linas** 2017-07-25 20:36 UTC
Labels: atomspace
